### ISSUE TITLE
Allow setting up padding in IEEE block header

### ISSUE THREAD

**Issue by wurbanski** [pyvisa/pyvisa#162]
When using write_binary_data(), IEEE header is being created properly, but there are some devices (eg. Keysight U253x family) which required the header to be of specified length, in this case <number of bytes> left-padded with zeros to 8 digits, eg. with data of 123456 bytes, the header should look like this:

```
#800123456
```

and instead it is formed (aligning with standards though) as:

```
#6123456
```

Adding a way of specifying the padding length would be really helpful when working with these devices.

**Comment by hgrecco** [comment]
Sorry for the delay but I completely missed this.

We could do with `write_binary_values` some similar to what is done in `query_binary_values`. There is an argument to control the header format (called `header_fmt`). You could add an option (`keysight`) that maps to the right format and change the code accordingly. I like that more than the padding as it allows for other formats in the future. You could add a padding option `to_ieee_block` which is an internal function

**Comment by hgrecco** [comment]
any interest in following this?

**Comment by wurbanski** [comment]
This time I must have missed it :)

I'd gladly submit a PR with this fix this next week if that's fine for you.
