### ISSUE TITLE
Question: trouble with rs232

### ISSUE THREAD

**Issue by GrahamWeatherup** [pyvisa/pyvisa#17]
Hi I am having trouble with RS232 Agilent E3642A PSU

I can connect and control (using send command) the device from the Agilent IO software but when I try to connect using pyVisa the device seems to error, I believe I have the port setup to use 2 stop bits, baud 9600, parity none 8 bits. I have the correct null modem cable from Agilent.

```
list=get_device_list()
```

is working correctly

I am controlling a signal generator via USB correctly
The PSU is COM7 (ASRL7) and I am trying to use the line 
    psu=instrument("ASRL7")
I did try 
    psu=instrument("ASRL7::INSTR")
    psu=instrument("ASRL7","stop_bits=2")
to no avail

What can I be doing wrong?

Is there a way to get Agilent IO(Agilent VISA library surely) to refresh all the devices as it seems to not find them If I have not done that first. Can I get serial settings from AgilentIO somehow?

Thanks

**Comment by charley43613** [comment]
>  I did get the problem fixed, it was basically setting the stop bits and term char
Where did you set your stop bits and terminating char. Pyvisa doesn't ask for this information when you're creating a resource object, it simply finds the port and attempts to open it as a visa object. I'm having issues understanding how to get any rs232 connection with pyvisa to work, but have had success with all other interfaces.(gpib, ethernet,usb, etc)
