### ISSUE TITLE
Implement wait_for_srq() for USB instruments.

### ISSUE THREAD

**Issue by rwalshEE** [pyvisa/pyvisa#203]
I am trying to get a USB instrument to send back a request for service but I cannot seem to be able to do this.  I tried going "lower level" but am running into a myriad of problems.  If this is already implemented, or if there's a way to do this already, it'd be a great tutorial to post.  Thanks again for the great software!

**Comment by MatthieuDartiailh** [comment]
Was this using pyvisa-py backend or National Instrument VISA ?

**Comment by bjaraujo** [comment]
https://stackoverflow.com/questions/37537927/python-pyvisa-with-usb-connection-wait-for-srq-or-wait-on-event
