### ISSUE TITLE
Find resource that is connected to 4-to-1USB hub

### ISSUE THREAD

**Issue by vciJson** [pyvisa/pyvisa#209]
I use 4-to-1 USB Hub ([D-Link DUB H7 Hub - 7 USB 2.0 Ports]) with MacBook Pro to connect multiple equipments and mobile devices because Macbook Pro is limited to 2 USB connection.

I connected D-link USB hub and connected iPhone and Android device to the hub.

See the connection hierarchy  through "ioreg -p IOSUSB"
+-o Root  <class IORegistryEntry, id 0x100000100, retain 14>
     +-o Root Hub Simulation Simulation@14000000  <class AppleUSBRootHubDevice, id 0x100000305, registered, matched, active, bu$
       +-o Apple Internal Keyboard / Trackpad@14400000  <class AppleUSBDevice, id 0x10000cf83, registered, matched, active, bus$
       +-o Bluetooth USB Host Controller@14300000  <class AppleUSBDevice, id 0x10000cf87, registered, matched, active, busy 0 ($
       +-o USB2.0 Hub@14200000  <class AppleUSBDevice, id 0x10000e28b, registered, matched, active, busy 0 (11 ms), retain 24>
         +-o USB HID@14210000  <class AppleUSBDevice, id 0x10000e2c5, registered, matched, active, busy 0 (13 ms), retain 20>
         +-o SAMSUNG_Android@14230000  <class AppleUSBDevice, id 0x10000e30d, registered, matched, active, busy 0 (20 ms), reta$
         +-o USB2.0 Hub@14250000  <class AppleUSBDevice, id 0x10000e36e, registered, matched, active, busy 0 (7 ms), retain 21>
         | +-o USB HID@14251000  <class AppleUSBDevice, id 0x10000e3df, registered, matched, active, busy 0 (6 ms), retain 20>
         +-o iPhone@14240000  <class AppleUSBDevice, id 0x10000e3d7, registered, matched, active, busy 0 (332 ms), retain 31>

pyvisa code to find out resources that are connected to MacBook Pro
import visa
resource_manager = visa.ResourceManager()
print resource_manager.list_resources()
print resource_manager.list_resources_info()

(u'ASRL1::INSTR', u'ASRL8::INSTR')
{u'ASRL8::INSTR': ResourceInfo(interface_type=<InterfaceType.asrl: 4>, interface_board_number=8, resource_class=u'INSTR', resource_name=u'ASRL8::INSTR', alias=None), u'ASRL1::INSTR': ResourceInfo(interface_type=<InterfaceType.asrl: 4>, interface_board_number=1, resource_class=u'INSTR', resource_name=u'ASRL1::INSTR', alias=None)}

It only found out the resource of USB port of Macbook Pro.

So, How to find out the resource of the devices that is connected to D-Link Hub?

Thanks,
Jinwoo Son

**Comment by MatthieuDartiailh** [comment]
Closing, feel free to re-open if there is more to discuss. If you re-open please specify what kind of device you are trying to access.
