### ISSUE TITLE
py2exe-compiled executable with optimizations fails

### ISSUE THREAD

**Issue by compholio** [pyvisa/pyvisa#214]
When optimizations are turned on with py2exe then PyVISA fails to import.  This same situation can be tested without using py2exe by turning on optimizations at the python command line:
`python -OO ./script.py`
Should you do this on a script that imports PyVISA then you'll see the error:

> TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

This problem results from the docstrings (`__doc__` attribute) not being populated when optimizations are enabled.  There are several ways to solve this problem, but the easiest is likely to check for `__doc__` being None before attempting to add to the documentation.

**Comment by MatthieuDartiailh** [comment]
Closing as I don't see any easy way around this, feel free to re-open if there is more to discuss

**Comment by compholio** [comment]
How about this?
[0001-Ensure-that-__doc__-exists-before-adding-to-it.patch.txt](https://github.com/pyvisa/pyvisa/files/1756601/0001-Ensure-that-__doc__-exists-before-adding-to-it.patch.txt)

**Comment by MatthieuDartiailh** [comment]
Could you make that into a pull request ?

**Comment by compholio** [comment]
Done (https://github.com/pyvisa/pyvisa/pull/318)
