### ISSUE TITLE
NI-USB 6009

### ISSUE THREAD

**Issue by zultras** [pyvisa/pyvisa#217]
Hey ! 

I'm trying to use NI-USB 6009 on Rasbperry PI 2 with python script. I installed Pyvisa and pyvisa-py on the Raspberry Pi. But now I don't know how to use this library to communicate with my DAQ in my script.

When I'm using  : 

> import visa
> rm=visa.ResourceManager('@py')
> print(rm.list_resources())

I got this error : 

`VisaIOError: VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.` 

I installed PyvisaUSB too.

Thx

**Comment by MatthieuDartiailh** [comment]
NI DAQ do not use VISA, you should try to give a look at https://nidaqmx-python.readthedocs.io/en/latest/.
Closing, feel free to re-open if there is more to discuss
