### ISSUE TITLE
Pyvisa adding \r\n to message

### ISSUE THREAD

**Issue by ghost** [pyvisa/pyvisa#220]
I am trying to communicate with Tektronix PA1000. I have verified that I can send and receive message from it using the NI tools, but when ever I try to use Pyvisa I get and error. using NI-trace I found the problem instead of sendinfg '*IDN?' I am sending 'IDN?..', the extra chars are \r\n. How can I remove this from the string I send? Here is my code and the what NI-trace us telling me .  
Thank you 

```
import visa
import time

rm = visa.ResourceManager() 
device_list =  rm.list_resources()
print device_list

device =  rm.open_resource(device_list[0],send_end=False)

device.query_ascii_values('*IDN?')
#print device.read()`
`import visa
import time

rm = visa.ResourceManager() 
device_list =  rm.list_resources()
print device_list

device =  rm.open_resource(device_list[0],send_end=False)

device.query_ascii_values('*IDN?')
#print device.read()
```
1.  viWrite (USB0::0x0699::0x4002::B0... (0x029E0A38), "*IDN?..", 7, 7)
   Process ID: 0x0002AB98         Thread ID: 0x0002A99C
   Start Time: 09:17:30.014       Call Duration 00:00:00.000
   Status: 0 (VI_SUCCESS)

![image](https://cloud.githubusercontent.com/assets/12775451/16416987/7457746a-3d12-11e6-8811-2e466b2ddf39.png)

**Comment by MatthieuDartiailh** [comment]
You can try setting write_termination to ''.
