### ISSUE TITLE
Basic "read" and "write" attribute doesn't work with PXIInstrument.

### ISSUE THREAD

**Issue by kp372** [pyvisa/pyvisa#222]
I am trying to work with PXI with pyvisa library. While working on I got to learn that "read" ,"write" attributes from GPIBinstrument doesn't work in PXIinstrument. 

Code 

```
import visa                                      #import NI Virtual Instrument Software Architecture
import time 
import pyvisa
rm = pyvisa.highlevel.ResourceManager()
rm.list_resources()                                     #import python time functionality
A = rm.open_resource("PXI2::14::INSTR")                  #create variable for instrument address
B = rm.open_resource("PXI2::6::INSTR") 
                                                                 #variable for voltage
print A.model_name
print B.model_name
A.write("F0,0X")

```

Error:

```
File "xxx.py", line 11, in <module>
A.write("F0,0X") # Force Force V measure I
AttributeError: 'PXIInstrument' object has no attribute 'write'

```

Thanks

**Comment by MatthieuDartiailh** [comment]
PXI are defined as registry based instrument not message based instrument hence the laking methods. Registry based instrument can only receive and send raw data (using move_in/out write/read_memory). However as I have never used a PXI instrument I do not know whether it makes sense to you.
