### ISSUE TITLE
Issue with 16-bit binary values and np.array containers

### ISSUE THREAD

**Issue by jonnojohnson** [pyvisa/pyvisa#237]
I'm using query_binary_values to get 16-bit binary data from a scope using the flags:
datatype = 'h'
container = np.array
However the numpy array ends up with int32 data type values (the values are correct but are wasting space) instead of int16.
I'm using PyVISA 1.8 on Python 2.7

**Comment by MatthieuDartiailh** [comment]
I believe this is fixed in 1.9. Please re-open if necessary.
