### ISSUE TITLE
Can anyone tell about Pyvisa internal architecture?

### ISSUE THREAD

**Issue by prakashmnnit81** [pyvisa/pyvisa#250]
I am  using Python  and PyVisa to Connect  the instrument. I am  not  able to understand how pyvisa is communicating with instrument internally with visa library.So can any body tell me about it internal architecture?

**Comment by gitjoost** [comment]
never heard of google?  https://pyvisa.readthedocs.io/en/stable/

**Comment by MatthieuDartiailh** [comment]
Closing as stale
