### ISSUE TITLE
how Pyvisa is fetching data when instrument generating  lot of data points?

### ISSUE THREAD

**Issue by prakashmnnit81** [pyvisa/pyvisa#251]
on my instrument i have generated data up 50K  when I am trying to fetch data  using Command 
rm=visa.ResourceManager()
my_instrument=rm.open_resource('USB0::0x0957::0x0A07::MY48001714::0::INSTR')
x=my_instrument.query('READ?')
it is returning data  into chunk or all data  or all data fetch simaltaneously

**Comment by MatthieuDartiailh** [comment]
Read will read up to the termination character. For binary answer, have a look at `read_binary_values`. Closing feel free to re-open if there is more to discuss
