### ISSUE TITLE
broken characters when reading from GPIB

### ISSUE THREAD

**Issue by volkers** [pyvisa/pyvisa#254]
I try to control a Keithley 2306 instrument by using GPIB in python. Basically the communication works but when reading from the instrument often characters are broken. E.g.:

`rm = visa.ResourceManager()`
`inst = rm.open_resource('GPIB0::5::INSTR')`
`inst.write_termination = '\n'`
`inst.query('*IDN?')`

gives
`'[EYTXLUY0I^STRUMUNTS0I^C>,]OTE\\ 2306,1178362,B16  /B02  \n'`

The same in National Instruments VISA Test Panel looks so instead:

3: Write Operation (*IDN?\n)

Return Count: 6 bytes

4: Read Operation
Return Count: 57 bytes
`KEITHLEY INSTRUMENTS INC.,MODEL 2306,1178362,B16  /B02  .`

When I check in NI I/O Trace both variants seem similar:

run command in NI Test Panel:

3.  viWrite (GPIB0::5::INSTR (0x01FBD908), "*IDN?.", 6, 6)
Process ID: 0x000013E0         Thread ID: 0x00001390
Start Time: 12:57:52.691       Call Duration 00:00:00.022
Status: 0 (VI_SUCCESS)

4.  viRead (GPIB0::5::INSTR (0x01FBD908), "KEITHLEY INSTRUMENTS ...", 1024, 57)
Process ID: 0x000013E0         Thread ID: 0x00001390
Start Time: 12:57:52.892       Call Duration 00:00:00.028
Status: 0 (VI_SUCCESS)

run in python as above:

5.  viWrite (GPIB0::5::INSTR (0x02B67068), "*IDN?.", 6, 6)
Process ID: 0x0000017C         Thread ID: 0x000007AC
Start Time: 10:27:22.794       Call Duration 00:00:00.013
Status: 0 (VI_SUCCESS)

6.  viRead (GPIB0::5::INSTR (0x02B67068), "[EYTXLUY0I^STRUMUNTS0...", 20480, 57)
Process ID: 0x0000017C         Thread ID: 0x000007AC
Start Time: 10:27:22.808       Call Duration 00:00:00.020
Status: 0 (VI_SUCCESS)

Maybe interesting also:

py -m visa info
Machine Details:
   Platform ID:    Windows-7-6.1.7601-SP1
   Processor:      x86 Family 6 Model 42 Stepping 7, GenuineIntel

Python:
   Implementation: CPython
   Executable:     C:\Users\vos\AppData\Local\Programs\Python\Python36-32\python.exe
   Version:        3.6.0
   Compiler:       MSC v.1900 32 bit (Intel)
   Bits:           32bit
   Build:          Dec 23 2016 07:18:10 (#v3.6.0:41df79263a11)
   Unicode:        UCS4

PyVISA Version: 1.8

Backends:
   ni:
      Version: 1.8 (bundled with PyVISA)
      #1: C:\Windows\system32\visa32.dll:
         found by: auto
         bitness: 32
         Vendor: National Instruments
         Impl. Version: 15728640
         Spec. Version: 5243904
      #2: C:\Windows\system32\visa32.dll:
         found by: auto
         bitness: 32
         Vendor: National Instruments
         Impl. Version: 15728640
         Spec. Version: 5243904

**Comment by MatthieuDartiailh** [comment]
It may be an encoding issue, but that looks weird. Given this is old, closing feel free to re-open if there is more to discuss
