### ISSUE TITLE
Extra . added after a TCP based VISA write using V 1.8

### ISSUE THREAD

**Issue by camerin** [pyvisa/pyvisa#257]
When i execute the following code to query a device id on a socket based  VISA connection:
`
import visa
tempInstance = rm.open_resource(""TCPIP0::192.168.100.254::24000::SOCKET")
instIDN=tempInstance.query('*IDN?')
`
I actually see transmitted to the visa instrument is "*IDN?.\n" using a visa connection monitor in keysite connection wizard.
![image](https://cloud.githubusercontent.com/assets/4407668/23146339/d669605e-f78a-11e6-95fe-070da548086b.png)

the added . breaks my commands to this instrument.

**Comment by dvincentwest** [comment]
Wow that's weird. If you change the write termination does it change the outcome?

**Comment by camerin** [comment]
If I send a write then read it is exactly the same. I have used USB instrument in the past with no issues like this

**Comment by dvincentwest** [comment]
I mean what happens if you change the string value for tempInstance.write_termination. For that matter can you check what the value is set to?

**Comment by camerin** [comment]
I will check when I get to the instrument.

**Comment by MatthieuDartiailh** [comment]
I have seen no such things in my recent testings. Closing feel free to re-open if there is more to discuss
