### ISSUE TITLE
reading binary input returns empty string

### ISSUE THREAD

**Issue by creilly** [pyvisa/pyvisa#26]
I used your library with the Tektronix TDS2000 USB oscilloscope, TekVisa, python 2.7, and Windows 7.

The CURV? query requests a waveform. Using a simple piece of a software written by Tektronix (OpenChoice Talker Listener) I can reliably obtain the binary waveform data. 

When issuing this command through pyvisa, however, I will quite often and unpredictably receive an empty string when using the "ask", "read", and "read_raw" methods of the VISA instrument object.

If I reconfigure the scope to return an ascii (as opposed to binary) representation of the waveform, pyvisa will work correctly, but it takes ~2 seconds to obtain a waveform (trigger rate on the scope is ~ 10 hz).

**Comment by tnsolley** [comment]
I am trying to setup and get results from a Mask Test using the Agilent MSO-X 3014A. I have installed the # KeySight Instrument Control Bundle 7.2017 (and all sub-items), yes upon running my program I am having the same IOError mentioned above. I didn't see any clear message about the cause or fix to this problem...

VisaIOError: VI_ERROR_INV_RSRC_NAME (-1073807342): Invalid resource reference specified. Parsing error.

Please do tell how I can diagnose and troubleshoot this problem further. 
The results of `python -c "from pyvisa import util; util.get_debug_info()` are

`Machine Details:
    Platform ID: Windows-7-6.1.7601-SP1
    Processor:    Intel64 Family 6 Model 70 Stepping 1, Genuine Intel

Python:
    Implementation: CPython
    Executable:  C:\Python27\python.exe
    Version:       2.7.13
    Compiler:    MSC v.1500 32 bit (Intel)
    Bits:             32bit
    Build:           Dev 17 2016 20:42:59 (#v2.7.13:a06454b1afa1)
    Unicode:      UCS2

PyVISA Version 1.8

Backends:
    ni:
        Version: 1.8 (bundled with PyVISA)
        #1:    C:\Windows\system32\visa32.dll:
                 found by:    auto
                 bitness: 32
                 Vendor: Keysight Technologies
                 Impl. Version:  1376087058
                 Spec. Version: 5243136
    #2:        C:\Windows\system32\visa32.dll:
                 found by: auto
                 bitness: 32
                 Vendor: Keysight Technologies
                 Impl.  Version: 1376087058
                 Spec. Version: 5243136`
