### ISSUE TITLE
AttributeError: 'VisaLibrary' object has no attribute 'viParseRsrcEx' 

### ISSUE THREAD

**Issue by schaefer0** [pyvisa/pyvisa#261]
Just curious, has this ever been fixed from 2014?
I'm getting this error in 2017

**Comment by MatthieuDartiailh** [comment]
Which version are you using and what command leads to this issue ?

**Comment by schaefer0** [comment]
Hi, Matthieu

From my notes: v1.8-2

 this was back in May 2017, I gave up switched to TCP/IP.

bob s.



On Nov 13, 2017, at 3:37 PM, Matthieu Dartiailh <notifications@github.com<mailto:notifications@github.com>> wrote:


Which version are you using and what command leads to this issue ?

**Comment by ClundXIII** [comment]
I am getting the same error when trying to access an oscilloscope. Both in 32 and 64 bit python3.

pyvisa version 1.8

**Comment by MatthieuDartiailh** [comment]
What VISA implementation are you using (National Instruments, Keysight, Tektronic, ...) ? This function should be implemented by the VISA library and I guess is implemented by at least some implementations as otherwise it would never work.

**Comment by schaefer0** [comment]
Googling the error message (months ago so my memory is hazy) I found that an earlier version worked but the attribute was removed in later versions.

On Nov 28, 2017, at 6:20 AM, Matthieu Dartiailh <notifications@github.com<mailto:notifications@github.com>> wrote:


What VISA implementation are you using (National Instruments, Keysight, Tektronic, ...) ? This function should be implemented by the VISA library and I guess is implemented by at least some implementations as otherwise it would never work.

**Comment by ClundXIII** [comment]
I am not sure. I have somewhat both installed, however the national instruments one only provides 32 bit libraries for Linux.
I will try to remove it and force the opensource package manager version. (I am on Linuxmint 18.2)

**Comment by MatthieuDartiailh** [comment]
All specifications I have found about VISA say that viParseRsrcEx should be implemented, which is why this issue surprises me.

**Comment by ClundXIII** [comment]
I have the following packages installed:
```
ii  libvisa-dev:amd64                                           0.0.20130812-2                                           amd64        Virtual Instrument Software Architecture (development files)
ii  libvisa0:amd64                                              0.0.20130812-2                                           amd64        Virtual Instrument Software Architecture (runtime files)
ii  python-pyvisa                                               1.8-2                                                    all          Python bindings for Virtual Instrument Software Architecture
ii  python-pyvisa-py                                            0.2-1                                                    all          Backend that implements a large part of the VISA in pure Python
ii  python3-pyvisa                                              1.8-2                                                    all          Python 3 bindings for Virtual Instrument Software Architecture
ii  python3-pyvisa-py                                           0.2-1                                                    all          Backend that implements a large part of the VISA in pure Python 3
```

(I specified the 64 bit library explicitly in the resource manager command to make sure I am using the correct one.)

**Comment by MatthieuDartiailh** [comment]
Apparently librevisa does not implement viParseRsrc (and neither viParseRsrcEx) (see here https://github.com/charlylima/LibreVisa/blob/master/README.md). I am not sure how to get around this.

**Comment by GyrosGeier** [comment]
I left that function out initially because all the Visa client code I had didn't use it. It should be trivial to implement, so while I'm sick in bed I can give it a poke.

**Comment by MatthieuDartiailh** [comment]
Sounds good  @GyrosGeier

**Comment by MatthieuDartiailh** [comment]
any progress on this @GyrosGeier

**Comment by MatthieuDartiailh** [comment]
ping @GyrosGeier

**Comment by GyrosGeier** [comment]
I've found a few minutes to work on this over the weekend.

Apparently I'd written the backend infrastructure for viParseRsrc/viParseRsrcEx back in 2012, but never connected it to the frontend methods, or implemented it in the transport plugins.

Still needs some work, as we have lots of duplicate code between parse/find/open, and I'd like to get rid of that before turning it into a release. In the same run, I'd also like to get a few more attributes supported (especially where the documentation for viParseRsrc says that return values need to correspond to attribute values).

**Comment by MatthieuDartiailh** [comment]
@GyrosGeier did you ever complete this work ?

Closing the issue since PyVISA is behaving as expected here. Feel free to re-open if necessary.

**Comment by kariminiaiman1** [comment]
[visa library](https://visalibrary.com/) is a site about visa and passport

**Comment by ben-lei** [comment]
@GyrosGeier, has this been addressed? I'm experiencing the same behavior

**Comment by adsherman09** [comment]
This is still happening to me in 2024, trying to connect to a USB device from an ubuntu computer.
