### ISSUE TITLE
pyvisa.exe for windows x64.

### ISSUE THREAD

**Issue by houmingc** [pyvisa/pyvisa#263]
I work in a secured environment; it means I have no internet access; I need to download into thumbdrive for installing. I am using window x64 and I need to install pyvisa onto this PC. I found Python Visa(x32) in sourceForge. My question: how to download pyvisa.exe for windows x64.

**Comment by DavidLutton** [comment]
pyvisa does not provide binarys as Python and therefore pyvisa is an interpreted language and is not compiled into a binary format. Like an .exe

Presumably you have obtained permission to add software to the secured environment 

Clone this repo using git to your thumb drive on a machine with internet access
git clone into a directory on the thumb drive, say 'Repos'
`git clone https://github.com/pyvisa/pyvisa.git`

On your isolated machine, presumably with a Python installation including pip
with the thumb drive showing up as E:/
`pip install --upgrade git+file://E:/Repos/pyvisa`

My slashes in the path / may be wrong on a Windows machine, it's been a while, correct as needed.
