### ISSUE TITLE
PyVISA has moved

### ISSUE THREAD

**Issue by hgrecco** [pyvisa/pyvisa#265]
PyVISA and its related project (pyvisa-py and pyvisa-sim) has been moved to its own organization.

**Comment by dvincentwest** [comment]
is there a link?

**Comment by hgrecco** [comment]
You are there already!

https://github.com/pyvisa/pyvisa

**Comment by dvincentwest** [comment]
ahhh! of course!  Thanks very much

**Comment by MatthieuDartiailh** [comment]
Who will be participating to the projects and is there a roadmap ?

**Comment by hgrecco** [comment]
@MatthieuDartiailh The idea is to turn it into a community project and hopefully you and others would like to join.

Regarding the roadmap, it is a community project so it is to the community to discuss and decide. I think there a few interesting things to move forward like asyncio.

**Comment by MatthieuDartiailh** [comment]
Count me in. I can't promise I will make large contributions in the near future but I will happily review any proposed changes (there is one pending PR on pyvisa-py for ethernet that deserves some attention !)

**Comment by hgrecco** [comment]
Awesome. By the way, I am using bors ng in pint to merge cleanly. We might give it a try for pyvisa as well

**Comment by MatthieuDartiailh** [comment]
Sounds like a reasonable idea to me. I will be waiting for an invitation.

**Comment by MatthieuDartiailh** [comment]
Bors seems to work on PyVisa-py (even though it appears a bit slow, by the way how can I check what it is doing). One thing that I find annoying however is not being able to edit the tag of an issue or to close it. There is quite large number of issues that need to be either addressed or closed and tagging would help prioritize. Could you give me those permissions ?

**Comment by MatthieuDartiailh** [comment]
This has been effective for several months now so closing.
