### ISSUE TITLE
Issue with query_binary_values

### ISSUE THREAD

**Issue by bjaraujo** [pyvisa/pyvisa#267]
I am using query_binary_values and it stops in messagebased.py:

```
            while len(block) < expected_length:
                block += self.read_raw()
```

It doesn't timeout although I have a timeout, it just stops. Initially, I thought I wasn't sending enough data but then I used raw sockets using `block = s.recv(32768)` and the data is there. I then pass the data to:  `util.from_ieee_block(block, 'h')` and everything works fine. I was trying to build a device using pyvisa-sim to reproduce this issue but since this is binary data not sure how to do it.

rm.open_resource('TCPIP::' + IP_ADDRESS + '::' + PORT + '::SOCKET', write_termination='\n', read_termination='\r')

I have read_termination='\r'. Is it looking for the terminator in binary mode?

EDIT: Seems to be the read_termination. I now open_resource without read terminator and then it works fine. But if I set up the instrument and then change it with `inst.read_termination = None` it still doesn't work in that case.

**Comment by MatthieuDartiailh** [comment]
Looking quickly at the code it does look like the VISA settings for the termination characters is not modified so I suspect it is indeed expecting a termination char. I have sadly no time to investigate on a real instrument.

**Comment by bjaraujo** [comment]
Hi, 

Thanks for the answer. 

I guess it is just not updating the read_termination character so if you open it with read_termination on it will be always expecting that.

I could make the change but I am not sure how to change the code as I am not familiar with pyVISA. I can also test if the change worked...

**Comment by bjaraujo** [comment]
Actually I think this might be an issue of the VISA driver so going to close.

**Comment by bjaraujo** [comment]
I think the bug is that read_raw only reads up to the termination character even if you specify:

inst.read_termination = None

**Comment by MatthieuDartiailh** [comment]
Are you using the ni backend or pyvisa-py ? in the second case could you try again with the latest master ? A number of fixes have been made to the tcpip-socket session. Also please note that in most cases, I have encountered the instrument send a termination character also when querying binary data. Could check the content of the bytes you get from the socket to assert it does not contain the termination.

**Comment by bjaraujo** [comment]
@MatthieuDartiailh 

Hi, I am using both. It seems read_raw always stops at byte 0x0A which I guess is the default terminator. 
Thanks for the tip though, I will certainly try the latest pyvisa-py.

**Comment by MatthieuDartiailh** [comment]
But even if read_raw stops the while loop should ensure that you get all your data.

**Comment by MatthieuDartiailh** [comment]
You can use the `read_bytes` method from PyVISA 1.9 to debug this further.
Closing feel free to re-open if there is more to discuss
