### ISSUE TITLE
Trying to set flow control to DTR/DSR

### ISSUE THREAD

**Issue by Toronto3** [pyvisa/pyvisa#268]
Hi all, I am trying to communicate with a multimeter using pyvisa however i cant seem to get a response and I think its because I need to set the correct flow control. Does anyone know where i can find a list of values for the flow_control value? Specifically for DTR/DSR.

Thanks!

**Comment by DavidLutton** [comment]
#242, #128

**Comment by MatthieuDartiailh** [comment]
The indicated issues answer the question. Closing feel free to re-open if there is more to discuss
