### ISSUE TITLE
Unsupported attributes for PyVISA-py TCPIP SOCKET communication

### ISSUE THREAD

**Issue by cwgamma** [pyvisa/pyvisa#274]
I am using  PyVISA and PyVISA-py on Ubuntu 16.04LTS. The device that I am attempting to communicate with over TCPIP requires socket communication and the following attributes: 
VI_ATTR_SEND_END_EN set to True and VI_ATTR_SUPPRESS_END_EN set to False, but these are not supported:

>>> import visa
>>> rm=visa.ResourceManager('@py')
>>> vna=rm.open_resource("TCPIP0::10.168.1.155::9001::SOCKET")
>>> vna.visalib.set_attribute(vna.session, visa.constants.VI_ATTR_SEND_END_EN, visa.constants.VI_TRUE)
<StatusCode.error_nonsupported_attribute: -1073807331>
>>> vna.visalib.set_attribute(vna.session, visa.constants.VI_ATTR_SUPPRESS_END_EN, visa.constants.VI_FALSE)
<StatusCode.error_nonsupported_attribute: -1073807331>

Is there another way to set these attributes, or is there a work around for them? 

I have tested this code successfully on Windows using the NI driver. For this project however, Ubuntu Linux is required, and I have not been able to install theLinux NI VISA driver with any success, and would prefer to use PyVISA-py as the backend.
I have also attempted to use the PyVISA-py-0.3.dev0 with no success. Here is the result of running

python -m visa info
Machine Details:
   Platform ID:    Linux-4.4.0-83-generic-x86_64-with-debian-stretch-sid
   Processor:      x86_64

Python:
   Implementation: CPython
   Executable:     /home/gpri2/anaconda2/bin/python
   Version:        2.7.13
   Compiler:       GCC 4.4.7 20120313 (Red Hat 4.4.7-1)
   Bits:           64bit
   Build:          Dec 20 2016 23:09:15 (#default)
   Unicode:        UCS4

PyVISA Version: 1.8

Backends:
   ni:
      Version: 1.8 (bundled with PyVISA)
      Binary library: Not found
   py:
      Version: 0.3.dev0
      ASRL INSTR:
         Please install PySerial to use this resource type.
         No module named serial
      TCPIP INSTR: Available 
      USB RAW:
         Please install PyUSB to use this resource type.
         No module named usb
      USB INSTR:
         Please install PyUSB to use this resource type.
         No module named usb
      GPIB INSTR:
         Please install linux-gpib to use this resource type.
         No module named gpib
      TCPIP SOCKET: Available 

Thanks

**Comment by MatthieuDartiailh** [comment]
This is a pyvisa-py issue I moved it.
