### ISSUE TITLE
Regular expression syntax is not documented

### ISSUE THREAD

**Issue by awneil** [pyvisa/pyvisa#280]
The Resource Manager documentation for list_resources() and list_resources_info() states that the 'query' parameter is a regular expression - but gives no definition or description or reference for the syntax of that regular expression

http://pyvisa.readthedocs.io/en/stable/api/resourcemanager.html#pyvisa.highlevel.ResourceManager.list_resources

I did eventually stumble upon this: https://github.com/pyvisa/pyvisa/blob/master/pyvisa/rname.py - which does contain a definition of the regular expression syntax.

It also points out that the regular expression syntax used here is **_not_** the same as the standard Python regular expression syntax - so it is all the more important that this should be stated in the documentation!

**Comment by awneil** [comment]
The VISA Resource Regular Expression is defined (with examples) in **VPP-4.3: The VISA Library specification** 
Section 4.4.1
Tables 4.4.1 - 4.4.4

http://www.ivifoundation.org/specifications/


See also:  http://zone.ni.com/reference/en-XX/help/370131S-01/ni-visa/findingvisaresourcesusingregularexpressions/

And: http://zone.ni.com/reference/en-XX/help/370131S-01/ni-visa/visaresourcesyntaxandexamples/

**Comment by MatthieuDartiailh** [comment]
Would you mind doing a pull request to add this to the docs ?

**Comment by awneil** [comment]
I wouldn't mind, but someone would have to walk me through that process - I don't do Git

**Comment by MatthieuDartiailh** [comment]
First you need to fork the repo (Fork button on the Github UI), then clone locally the forked repository (that you own). Create a new branch (regular-docs could be a good name but it does not really matter). Update the documentation files that need to be updated. Then commit your changes and push them to your repo. Once this is done the Github UI on your repo will ask you if you want to open a PR, just click on the button. If you are looking for git graphical interface, I would recommend Smartgit.

**Comment by awneil** [comment]
OK ...

**Comment by MatthieuDartiailh** [comment]
If you have more questions do not hesitate. Actually another simpler option would be to fork the project then simply edit the docs directly on Github, once you are done Github will handle the commit and branch creation for you and you will just have to create the PR.
If you can't do it I will probably do it at some point but I cannot say when.

**Comment by awneil** [comment]
Is it sufficient just to update the docstrings for list_resources() and list_resources_info() in pyvisa/highlevel.py ?

**Comment by MatthieuDartiailh** [comment]
I think that it is sufficient. The fact that one can filter the resources is not mentioned anywhere in the docs, which should also probably be fixed by adding a note in the tutorial. If you are familiar with sphinx (the tool used to build the documentation) you can add one. Otherwise I will add it to your PR myself.

**Comment by MatthieuDartiailh** [comment]
@awneil are you still planning to work on this ?

**Comment by awneil** [comment]
oops!  thanks for the riminder - yes!

**Comment by MatthieuDartiailh** [comment]
ping @awneil

**Comment by MatthieuDartiailh** [comment]
ping @awneil

**Comment by MatthieuDartiailh** [comment]
ping @awneil

**Comment by MatthieuDartiailh** [comment]
ping @awneil

**Comment by awneil** [comment]
I hope that's it ... ?

**Comment by MatthieuDartiailh** [comment]
Closed by #320
