### ISSUE TITLE
pyvisa.errors.LibraryError: Error while accessing visa32.dll: [Error 126]

### ISSUE THREAD

**Issue by h8d9123** [pyvisa/pyvisa#291]
**code:**
import visa
rm = visa.ResourceManager("visa32.dll")

**- error:**
File "<string>", line 1, in <module>
File "C:\Python27\lib\site-packages\pyvisa\highlevel.py", line 226, in __new__
  visa_library = VisaLibrary(visa_library)
File "C:\Python27\lib\site-packages\pyvisa\highlevel.py", line 102, in __new__
  raise errors.LibraryError.from_exception(exc, library_path)
visa.errors.LibraryError: Error while accessing visa32.dll: [Error 126]

**some info:**
Machine Details:
   Platform ID:    Windows-7-6.1.7601-SP1
   Processor:      x86 Family 6 Model 78 Stepping 3, GenuineIntel

Python:
   Implementation: CPython
   Executable:     C:\Python27\python.exe
   Version:        2.7.9
   Compiler:       MSC v.1500 32 bit (Intel)
   Bits:           32bit
   Build:          Dec 10 2014 12:24:55 (#default)
   Unicode:        UCS2

VISA:
   PyVISA Version: 1.5

   Not found.

 I tried pyvisa1.5 and 1.8, but the results are same.

**Comment by MatthieuDartiailh** [comment]
Not sure what is happening here. Why do you specify the visa implementation to use ? Usually Pyvisa does the right thing an pick up the proper dll. Also did you post the full error message ? it looks truncated to me.

**Comment by h8d9123** [comment]
thank you,MatthieuDartiailh .
this is all info:
>>> import visa
>>> rm = visa("visa32.dll")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
>>> rm = visa.ResourceManager("visa32.dll")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pyvisa\highlevel.py", line 226, in __new__

    visa_library = VisaLibrary(visa_library)
  File "C:\Python27\lib\site-packages\pyvisa\highlevel.py", line 102, in __new__

    raise errors.LibraryError.from_exception(exc, library_path)
pyvisa.errors.LibraryError: Error while accessing visa32.dll: [Error 126]

**Question:**
the software ,ni-visa, is necessary?
pyvisa can be use when ni-visa is installed. but I just want to use some about gpib.

**Comment by MatthieuDartiailh** [comment]
To communicate through GPIB on windows you need to install the VISA library (that pyvisa simply calls). You do not need the full National instrument stack but you do need ni-visa (or another implementation of visa).

**Comment by h8d9123** [comment]
Thank you very much, MatthieuDartiailh
