### ISSUE TITLE
Error during write_binary_values()

### ISSUE THREAD

**Issue by svanan77** [pyvisa/pyvisa#312]
Hi All,

I am trying to 
a) connect to a signal generator (Agilent N5182A MXG) that supports ASCII range(256) using TCPIP. 
b) set a signal waveform to the signal generator (siggen) using IQ data
c) select the signal waveform from the siggen.

Step a) and b) in the above are successful. The _StatusCode Success: 0_ returned. Unfortunately the siggen is complaining when step c) was executed, as below,

![image](https://user-images.githubusercontent.com/20521720/35594871-89be69c2-05c9-11e8-83f9-3588d95b01cb.png)

At the pyVisa side _StatusCode Success: 0_ was returned.

According to the below link, error 230 indicates a new reading has started but not completed, pointing to possible incorrect header formation.
Refer: http://na.support.keysight.com/pna/help/latest/Support/SCPI_Errors.htm

No timeout occurred during Step b). Nevertheless increased the timeout to 1000ms, just to be on safe side.

At the siggen, I have validated the number of points, 510, and found it is accurate (i.e 2040/4 = 510). 4 bytes are used per IQ data and 2040 bytes of data string, _iq_str_ is transferred to the siggen.

![image](https://user-images.githubusercontent.com/20521720/35595227-d0172e80-05ca-11e8-99a2-bfc9e92dc47b.png)

Have manually also validated the content of the transmitted _iq_str_ variable. All seems good. 

Have anyone faced this problem?

The full code is provided as below and the std_out of some of the important variables are shown as comments including the data string of _iq_str_ variable. 2 bytes seems unaccounted, maybe additional white space in the syntax. Not sure of this could be a cause. 

Hope to get your opinion on this. 
Though strange, I am sure it must have a reasonable answer. Keen to understand the reason for this.

```
import visa
import numpy
import itertools
import pylab as pl
import math
import os

#######################################
# Variables
#######################################

IP_SG = '10.10.100.131'
siggen_filename ='myCombSig'
num_tone=16
num_smpl_tone=32 

#######################################
# Initialization
#######################################

rm = visa.ResourceManager('@py')

#######################################
# Helper Functions
#######################################

def df_open_connection(rm, ip):
	inst = rm.open_resource('TCPIP::'+ ip + '::INSTR')
	return inst

def df_close_connection(inst):
	inst.close()

def df_my_range(start, end, step):
	while start <= end:
		yield start
		start += step

def df_Comb_sig_gen(num_tone, num_smpl_tone):
	comb_real = []
	comb_imag = []
	comb_cmpx = []
	M = num_tone * num_smpl_tone
	N = 0
	C = num_tone
	k = pl.frange(float(-(C - 1)) / 2, float((C - 1)) / 2, 1)
	for n in df_my_range(-N + 1, M + N - 2, 1):
		cc = numpy.exp(2j * math.pi * k * numpy.array(n) / (C))
		comb_cmpx.append(numpy.sum(cc))  

	comb_cmpx = numpy.array(comb_cmpx)

	return (comb_cmpx)

def df_set_waveform(comb_signal, filename):

	scale  = numpy.amax([numpy.amax(comb_signal.real),numpy.amax(comb_signal.imag)])

	comb_signal_real_scale = numpy.array(comb_signal.real)/scale
	comb_signal_imag_scale = numpy.array(comb_signal.imag)/scale

	i = comb_signal_real_scale
	q = comb_signal_imag_scale

	i_dac = map(lambda x: int(32767 * abs(x)), i)
	q_dac = map(lambda x: int(32767 * abs(x)), q)

	#Big Endian: bit masking and shifting. 
	iq_str = ""
	for i_val, q_val in itertools.izip(i_dac, q_dac):
		iq_str += chr((i_val >> 8) & 0x00FF) #e.g 32767 (0x7FFF) -> 7F
		iq_str += chr(i_val & 0x00FF)		 #e.g 32767 (0x7FFF) -> FF
		iq_str += chr((q_val >> 8) & 0x00FF)
		iq_str += chr(q_val & 0x00FF)

	scpi_command = ':MEM:DATA "WFM1:{}",'.format(filename.upper())
	
	return scpi_command, iq_str

def df_timeout(inst):
	delay = 10000 	# in milisecond
	inst.timeout = delay

def df_select_waveform(filename):
	"""
	Selects a waveform file in the signal generator's volatile memory.
	After selecting a waveform file, it can be played by calling enable_waveform().
	"""

	scpi_command = ':RAD:ARB:WAV "WFM1:{}"\n'.format(os.path.basename(filename).upper())

	return scpi_command

#################################################
# Action: To Set a Waveform on Signal Generator
#################################################

inst_sg = df_open_connection(rm, IP_SG)
inst_sg.write(':FREQ 1.8825 GHz; POWer -30DBM')
df_timeout(inst_sg)

comb_signal = df_Comb_sig_gen(float(num_tone),float(num_smpl_tone))	

set_waveform, iq_str = df_set_waveform(comb_signal, siggen_filename)
select_waveform = df_select_waveform(siggen_filename) #Data

df_timeout(inst_sg)

response_write = inst_sg.write_binary_values(set_waveform, iq_str, datatype='c')
#> response_write -> (2075, <StatusCode.success: 0>)

#> Format -> MMEM:DATA “WFM1:my_file”,#3 240 12%S!4&07#8g*Y9@7...
#> len(set_waveform) -> 27
#> len('#') -> 1
#> len('4') -> 1
#> len('2040') -> 4
#> len(iq_str) -> 2040
#> 2075 - (27+1+1+4+2040) = 2 bytes unaccounted for. Maybe used to parse 'datatype', 'is_big_endian', 'termination' and 'encoding' default parameters to Signal Generator

# The complete iq_str's ASCII data is given below. 
#> iq_str=                                                             ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                              ÿ                                                          

response_select = inst_sg.write(select_waveform)
#> response_select -> (32, <StatusCode.success: 0>)

df_close_connection(inst_sg)

```

The output of "python -m visa info"

```
Machine Details:
   Platform ID:    Linux-4.4.0-92-generic-x86_64-with-debian-stretch-sid
   Processor:      x86_64

Python:
   Implementation: CPython
   Executable:     /opt/anaconda2/bin/python
   Version:        2.7.12
   Compiler:       GCC 4.4.7 20120313 (Red Hat 4.4.7-1)
   Bits:           64bit
   Build:          Jul  2 2016 17:42:40 (#default)
   Unicode:        UCS4

PyVISA Version: 1.8

Backends:
   ni:
      Version: 1.8 (bundled with PyVISA)
      #1: /usr/lib/x86_64-linux-gnu/libvisa.so.0.0.0:
         found by: auto
         bitness: 64
         Could not get more info:
            VI_ERROR_NSUP_ATTR (-1073807331): The specified attribute is not defined or supported by the referenced object.
   py:
      Version: 0.3.dev0
      ASRL INSTR: Available via PySerial (3.4)
      TCPIP INSTR: Available 
      USB RAW: Available via PyUSB (1.0.2). Backend: N/A
      USB INSTR: Available via PyUSB (1.0.2). Backend: N/A
      GPIB INSTR:
         Please install linux-gpib to use this resource type.
         No module named gpib
      TCPIP SOCKET: Available 
   sim:
      Version: 0.3
      Spec version: 1.1
```

**Comment by svanan77** [comment]
I have validated the additional 2 bytes are due to the termination characters (CR and LF) inserted to the SCPI command. Still trying to understand how the Header could be not recognized.

**Comment by bjaraujo** [comment]
Hi,

I think pyVisa has some issue with reading/writing binary data and termination. 

In your case specifically I don't think you should be sending CRLF and the "reader" of this data should not "look" at termination characters either. The number of bytes is specified in the header so adding termination will only confuse the reader since it will stop when it sees a termination character. So might stop in the middle of binary data.

**Comment by MatthieuDartiailh** [comment]
There is nothing pointing clearly to the termination character being the issue here, even though it may be. One thing you can easily try is to simply query the waveform you just set to check you get the proper values.
If you can, try to use the ni backend (which most likely mean you need to access a windows machine). The pure python backend still has some bugs. 
In any case, I believe you could simplify your code by letting the python do all the packing. To do so, you could create a numpy array with you interlaced 16-bit integers and then passing it to write_binary_values as follow:
```python
data = np.array(2*len(i_dac)
data[::2] = i_dac
data[1::2] = q_dac
inst_sg.write_binary_values(set_waveform, data, datatype='H', is_big_endian=True)
```
I am also surprised by the way you build your data. Why use abs ? Usually one shifts the data so that they all become positive and normalize them afterwards. Here your negative values become positive which mean that you distort your waveform, and I doubt it is what you want.

**Comment by svanan77** [comment]
Hi,

Sorry for the late reply as I have been away. Thanks for your time. I will try to provide as complete information as possible.

@bjaraujo -- Referring to my code above, I did not send CR and LF termination characters in my code. When I validated the below line, the response returned 2075 bytes being sent. It had 2 byte unaccounted for which I later learned that pyVisa adds them automatically. Now all 2075 bytes are accounted for.

    response_write = inst_sg.write_binary_values(set_waveform, iq_str, datatype='c')
    #> response_write -> (2075, <StatusCode.success: 0>)

 @MatthieuDartiailh -- This could be a reason, let me elaborate in 3 parts.

a) I am keen to generate a 16 tone ideal flat comb signal where I feed this to the signal generator. 

    i_dac = map(lambda x: int(32767 * x), i)
    q_dac = map(lambda x: int(32767 * x), q)

The above creates the below signal stream

![image](https://user-images.githubusercontent.com/20521720/35992000-d7a08422-0cbd-11e8-859d-3822b091e2cc.png)


As can be seen in my data stream below,

    i_dac = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    q_dac = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

As I was looking for ideal flat comb signal with only positive tones, I included `abs()` as below,

    i_dac = map(lambda x: int(32767 * abs(x)), i)
    q_dac = map(lambda x: int(32767 * abs(x)), q)

The above creates the below signal stream,

![image](https://user-images.githubusercontent.com/20521720/35992004-dcc53b78-0cbd-11e8-8904-b81a8f7824a3.png)


As can be seen in my data stream below,

    i_dac = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32766, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32766, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32766, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32766, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32766, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32766, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32766, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32766, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32766, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32766, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32766, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32766, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32766, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32766, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32766, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32766, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    q_dac = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

b) When I use the below modified df_set_waveform() function (your suggestion + `abs()` ), 

    def df_set_waveform(comb_signal, filename):

        scale  = numpy.amax([numpy.amax(comb_signal.real),numpy.amax(comb_signal.imag)])

        i = numpy.array(comb_signal.real)/scale
        q = numpy.array(comb_signal.imag)/scale

        i_dac = map(lambda x: int(32767 * abs(x)), i)
        q_dac = map(lambda x: int(32767 * abs(x)), q)

        data = numpy.empty(2*len(i_dac))
        data[0::2] = i_dac
        data[1::2] = q_dac

        scpi_command = ':MEM:DATA "WFM1:{}",'.format(filename.upper())
	
        return scpi_command, iq_str

with,

    inst_sg.write_binary_values(set_waveform, data, datatype='h', is_big_endian=True)

the response seen at the spectrum analyzer is as below,

![image](https://user-images.githubusercontent.com/20521720/35991859-61525372-0cbd-11e8-931f-ba01da760f95.png)

For 16 tones generated, we can see 17 tones shown. The middle frequency is prominent.

When abs() removed, the below good response can be seen,

![image](https://user-images.githubusercontent.com/20521720/35992252-9e0c7ee0-0cbe-11e8-8b12-738587f83158.png)

What happened was, when `abs()` was used it generated tones as shown in red below and shifted by `+/- 1/2Fs` and included the `Fc` tone

![image](https://user-images.githubusercontent.com/20521720/35992468-2dae5118-0cbf-11e8-9e11-4a4ea1a86965.png)

c) I have tested in Matlab, applied abs in the below line 

    scale = max(max(abs(real(IQData))), max(abs(imag(IQData))));

It produced exactly same as the good response we obtained in the python code as shown in figure below,

![image](https://user-images.githubusercontent.com/20521720/35993230-7f2d0906-0cc1-11e8-9e00-a0af6a542f58.png)

The full Matlab code is produced at the end of this writeup. Do you have any idea why `abs()` is treated differently by pyVisa?

Full Matlab Code:

    %%%%%%%%%%%%%%%%%%%%%%%%%%Create the Complex Baseband Signal
    sampleRate = 199.68e+06/2;        % Define sample rate of baseband signal (Hz)
    Fs =  sampleRate;
    num_tone = 16;
    num_smpl_tone = 32;
    IQData=comb_signal(num_tone,num_smpl_tone);%/num_tone;

    scale = max(max(abs(real(IQData))), max(abs(imag(IQData))));
    idealPulse = IQData / scale;
    idealPulse = [ idealPulse ];

    ArbFileName = 'myCombSignal';
    MXGIPAddress = '10.10.100.131';

    signalGeneratorObject = visa('agilent',['TCPIP0::' MXGIPAddress '::inst0::INSTR']);
    signalGeneratorObject.OutputBufferSize = 4*numel(idealPulse) + 1024;
    signalGeneratorObject.ByteOrder = 'bigEndian';
    signalGeneratorObject.Timeout = 10.0;
    signalGeneratorObject.EOSCharCode = 'LF';
    fopen(signalGeneratorObject);


    %%%%%%%%%%%%%%%%%%%%Format Data to Meet Instrument Requirements
    % Ensure the waveform is a row vector.
    if ~isequal(size(idealPulse,1),1)
        idealPulse = reshape(idealPulse,1,numel(idealPulse));
    end

    % Separate out the real and imaginary data in the baseband signal.
    wave = [real(idealPulse);imag(idealPulse)];
    
    % Transpose the waveform to interleave I & Q data.
    wave = wave(:)';
    scale = 2^15-1;
    wave = round(wave * scale);
    modval = 2^16;
    wave = mod(modval + wave, modval);
    
    % Convert from double to unsigned int datatype.
    wave = uint16(wave);
    
    
    %%%%%%%%%%%%%%%%%%%%%Query Instrument Identification Information
    % Empty instrument error queue and event registers and reset the instrument.
    fprintf(signalGeneratorObject, '*CLS');
    fprintf(signalGeneratorObject, '*RST');
    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%Download Data to the Instrument
    % Turn off instrument before downloading waveform.
    fprintf(signalGeneratorObject,':OUTPut:STATe OFF');
    fprintf(signalGeneratorObject,':SOURce:RADio:ARB:STATe OFF');
    fprintf(signalGeneratorObject,':OUTPut:MODulation:STATe OFF');
    % Set the sample rate of the ARB clock to the sample rate of the baseband
    % signal.
    fprintf(signalGeneratorObject,[':SOURce:RADio:ARB:CLOCk:SRATe ' num2str(sampleRate)]);
    % Write the data to the unprotected non-volatile memory of the instrument.
    binblockwrite_dali(signalGeneratorObject,wave,'uint16', [':MEM:DATA:UNProtected "WFM1:'     ArbFileName '",']);
    % The signal generator expects an LF character at the end of the binaryblock.
    % By printing a null string with the EOS character set to LF, this byte will
    % be sent to the signal generator.
    fprintf(signalGeneratorObject,'');
    commandCompleted = query(signalGeneratorObject,'*OPC?');
    disp('...done');
    

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%Initiate Playback of the RF Signal on the     Instrument
    % Set the carrier frequency of the upconverted signal.
    fprintf(signalGeneratorObject, ':SOURce:FREQuency 1000000000');
    % Set the source power to -30dBm.
    fprintf(signalGeneratorObject, ':SOURce:POWer -20DBM');
    % Select the waveform and initiate generation.
    fprintf(signalGeneratorObject,[':SOURce:RADio:ARB:WAV "ARBI:' ArbFileName '"']);
    fprintf(signalGeneratorObject,':SOURce:RADio:ARB:STATe ON');
    fprintf(signalGeneratorObject,':OUTPut:MODulation:STATe ON');
    fprintf(signalGeneratorObject,':OUTPut:STATe ON');


    %%%%%%%%%%%%%%%%%%%%Check for Errors in the Instrument Error Queue
    % Read back and display any instrument errors.
    instrumentError = query(signalGeneratorObject,'SYST:ERR?');
    while isempty(strfind(lower(instrumentError),'no error'))
        fprintf('\tINSTRUMENT ERROR: %s', instrumentError)
        instrumentError = query(signalGeneratorObject,'SYST:ERR?');
    end


    %%%%%%%%%%%%%%%%%%%%%Clean Up
    % Close the connection to the instrument and delete the object.
    fclose(signalGeneratorObject); delete(signalGeneratorObject);
    clear signalGeneratorObject`

**Comment by MatthieuDartiailh** [comment]
I am not sure what is going there. Looking at the documentation from keysight I get the proper formatting for the values using PyVISA commands. Could you print the binary block before sending using both Matlab and Python (for both versions) (you can use the to_ieee_block from pyvisa.util to build the string), I am curious to see what differs between them.

**Comment by svanan77** [comment]
I shall update you tomorrow when I get slot to test this. Thanks for your time.
I have another basic query which I will post separately to not mix with this issue. Just to learn your expertise.

**Comment by MatthieuDartiailh** [comment]
Any news @svanan77 ?

**Comment by svanan77** [comment]
Hi @MatthieuDartiailh -- I managed to the slot to test this. I have confirmed it is a hardware issue and not of pyVisa. As when I use a different siggen of same make and model the same script works. I believe there are some issue with the volatile memory location of the siggen. Have forwarded this finding to the team member who is responsible to check further on this. Will close this.
