### ISSUE TITLE
Getting Frequency domain IQ Data from Signal Analyzer

### ISSUE THREAD

**Issue by svanan77** [pyvisa/pyvisa#313]
Do you have experience in reading frequency domain IQ data and storing it in csv format (or any other) within (or not) the signal generator? There are less writeup available on this and hence keen to learn from your expertise..

I am using N9010A Agilent EXA Signal Analyzer. 
Refer: http://literature.cdn.keysight.com/litweb/pdf/N9060-90029.pdf

In Spectrum Analyzer Mode, I am able to capture the trace into csv file using,

    rm = visa.ResourceManager('@py')
    sa_ip = '10.10.10.100'
    inst = rm.open_resource('TCPIP::'+ sa_ip + '::INSTR')
   inst.write('MMEM:STOR:TRAC:DATA ALL, "filename.csv"')

Similarly, in IQ Analyzer Mode, assume I am already in Complex Spectrum and I am keen to capture the frequency domain IQ trace. Tried to use the below syntax but not successful,

    inst.write(':MMEM:STOR:RES:MTAB "filename.csv"')

and `inst.write('TRACe1:IQ:DATA?) `no longer supported.

How do you get the frequency domain IQ data from the Signal Analyzer?

p/s: Not sure if this query fits the objective of our site. If it doesn't, I will remove this as soon as I learn this.

**Comment by MatthieuDartiailh** [comment]
Sorry I have never used this instrument and from the documentation I do not see any clear path onward. You probably should ask your question on a Keysight forum, they would be more likely to give you an answer. Closing as this is unrelated to pyvisa.
