### ISSUE TITLE
Query IQ Data from Signal Generator

### ISSUE THREAD

**Issue by svanan77** [pyvisa/pyvisa#316]
Hi,

I would like to pull IQ Data from the Signal Generator (Agilent Technologies, N5182A (Option 654), MY50140960, A.01.85).

According to the manual (as below), I can query using `:MEMory:DATA:IQ? "<file_name>"` syntax.

![image](https://user-images.githubusercontent.com/20521720/36287051-63b0bd16-1267-11e8-9445-585b7d5d9b18.png)

Have written the below code to pull the IQ of `waveform_file` already in the Signal Generator.

    IP_SG = '10.10.100.131'
    rm = visa.ResourceManager('@py')
    inst = rm.open_resource('TCPIP::'+ IP_SG + '::INSTR')
    inst.timeout = 30000
    print("Session ID : %s" % (inst.session))
    print("Instrument identification information : %s" % (inst.query("*IDN?").rstrip()))
    data = inst.query_binary_values(:MEMory:DATA:IQ? "waveform_file")

Unfortunately getting timeout error, eventhough the timeout is 30s currently.

![image](https://user-images.githubusercontent.com/20521720/36287307-ea379e8a-1268-11e8-9226-9124debca663.png)

As the output is not entirely float, I dont think it require for a `datatype` or `is_big_endian` to be specificied in the ` inst.query_binary_values()`. I even tried  ` inst.query()` which results in the same timeout error.

Do you happen to face the same problem before?

Saravanan K

**Comment by MatthieuDartiailh** [comment]
I note you are using the pyvisa-py backend. I identified recently a bug in the handling of the termination character for TCPIP. I fixed it in https://github.com/pyvisa/pyvisa-py/pull/126 but I did not merge yet. Could you try installing that branch ? Also can you retrieve any data from your instrument such as *IDN? ?

**Comment by svanan77** [comment]
Hi @MatthieuDartiailh,

Yes I am using pyvisa-py backend. I installed it using `pip install pyvisa-py` (not `git clone`).

I went through #126, perhaps that could be the case. 

Would be glad to test the branch. Unfortunately not familiar on how. Could you please list out the steps I need to do to test the branch?

If I'd installed pyvisa-py via `git clone`, I would have `git pull` it. I unable to do it that way for the below reason,

    svanan@svds07:~/ubuntu/pyvisa/pyvisa-py-master$ git status
    fatal: Not a git repository (or any parent up to mount point /home/svanan)
    Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

Otherwise, 

    print("Session ID : %s" % (inst.session))
    print("Instrument identification information : %s" % (inst.query("*IDN?").rstrip()))

gives the below output, will get the same output again after installing the new patch from #126.

    Session ID : 5097654
    Instrument identification information	: Agilent Technologies, N5182A, MY50140960, A.01.85

**Comment by MatthieuDartiailh** [comment]
To instal you can first do `pip uninstall pyvisa-py` and then `pip install https://github.com/MatthieuDartiailh/pyvisa-py/tarball/fixes`.

**Comment by svanan77** [comment]
Hi @MatthieuDartiailh,

I have done the validation and would present it in 2 parts, a) the preparation, b) the test

** A. The Preparation**

Step 1:

    svanan@svds07:~/ubuntu/pyvisa$ python -m visa info
    Machine Details:
      Platform ID:    Linux-4.4.0-92-generic-x86_64-with-debian-stretch-sid
      Processor:      x86_64

    Python:
      Implementation: CPython
      Executable:     /opt/anaconda2/bin/python
      Version:        2.7.12
      Compiler:       GCC 4.4.7 20120313 (Red Hat 4.4.7-1)
      Bits:           64bit
      Build:          Jul  2 2016 17:42:40 (#default)
      Unicode:        UCS4

    PyVISA Version: 1.8

    Backends:
      ni:
         Version: 1.8 (bundled with PyVISA)
         #1: /usr/lib/x86_64-linux-gnu/libvisa.so.0.0.0:
            found by: auto
            bitness: 64
            Could not get more info:
               VI_ERROR_NSUP_ATTR (-1073807331): The specified attribute is not defined or supported by the referenced object.
      py:
         Version: 0.3.dev0
         ASRL INSTR: Available via PySerial (3.4)
         TCPIP INSTR: Available
         USB RAW: Available via PyUSB (1.0.2). Backend: N/A
         USB INSTR: Available via PyUSB (1.0.2). Backend: N/A
         GPIB INSTR:
            Please install linux-gpib to use this resource type.
            No module named gpib
         TCPIP SOCKET: Available
      sim:
         Version: 0.3
         Spec version: 1.1

Step 2:

    svanan@svds07:~/ubuntu/pyvisa$ pip uninstall pyvisa-py
    Uninstalling PyVISA-py-0.3.dev0:
     /opt/anaconda2/lib/python2.7/site-packages/PyVISA_py-0.3.dev0-py2.7.egg-info
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/__init__.py
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/__init__.pyc
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/common.py
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/common.pyc
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/gpib.py
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/gpib.pyc
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/highlevel.py
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/highlevel.pyc
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/protocols/__init__.py
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/protocols/__init__.pyc
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/protocols/rpc.py
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/protocols/rpc.pyc
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/protocols/usbraw.py
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/protocols/usbraw.pyc
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/protocols/usbtmc.py
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/protocols/usbtmc.pyc
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/protocols/usbutil.py
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/protocols/usbutil.pyc
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/protocols/vxi11.py
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/protocols/vxi11.pyc
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/serial.py
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/serial.pyc
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/sessions.py
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/sessions.pyc
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/tcpip.py
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/tcpip.pyc
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/testsuite/__init__.py
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/testsuite/__init__.pyc
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/usb.py
     /opt/anaconda2/lib/python2.7/site-packages/pyvisa-py/usb.pyc
    Proceed (y/n)? y
     Successfully uninstalled PyVISA-py-0.3.dev0
    You are using pip version 8.1.2, however version 9.0.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.

Step 3:

    svanan@svds07:~/ubuntu/pyvisa$ python -m visa info
    Machine Details:
       Platform ID:    Linux-4.4.0-92-generic-x86_64-with-debian-stretch-sid
       Processor:      x86_64

    Python:
       Implementation: CPython
       Executable:     /opt/anaconda2/bin/python
       Version:        2.7.12
       Compiler:       GCC 4.4.7 20120313 (Red Hat 4.4.7-1)
       Bits:           64bit
       Build:          Jul  2 2016 17:42:40 (#default)
       Unicode:        UCS4

    PyVISA Version: 1.8

    Backends:
       ni:
          Version: 1.8 (bundled with PyVISA)
          #1: /usr/lib/x86_64-linux-gnu/libvisa.so.0.0.0:
             found by: auto
             bitness: 64
             Could not get more info:
                VI_ERROR_NSUP_ATTR (-1073807331): The specified attribute is not defined or supported by the referenced object.
       sim:
          Version: 0.3
          Spec version: 1.1

Step 4:

    svanan@svds07:~/ubuntu/pyvisa$ pip install https://github.com/MatthieuDartiailh/pyvisa-py/tarball/fixes
    Collecting https://github.com/MatthieuDartiailh/pyvisa-py/tarball/fixes
      Downloading https://github.com/MatthieuDartiailh/pyvisa-py/tarball/fixes
         \ 61kB 428kB/s
    Requirement already satisfied (use --upgrade to upgrade): pyvisa>=1.8 in /opt/anaconda2/lib/python2.7/site-packages (from PyVISA-py==0.3.dev0)
    Requirement already satisfied (use --upgrade to upgrade): enum34 in /opt/anaconda2/lib/python2.7/site-packages (from pyvisa>=1.8->PyVISA-py==0.3.dev0)
    Installing collected packages: PyVISA-py
      Running setup.py install for PyVISA-py ... done
    Successfully installed PyVISA-py-0.3.dev0
    You are using pip version 8.1.2, however version 9.0.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.

Step 5:

    svanan@svds07:~/ubuntu/pyvisa$ python -m visa info
    Machine Details:
       Platform ID:    Linux-4.4.0-92-generic-x86_64-with-debian-stretch-sid
       Processor:      x86_64

    Python:
       Implementation: CPython
       Executable:     /opt/anaconda2/bin/python
       Version:        2.7.12
       Compiler:       GCC 4.4.7 20120313 (Red Hat 4.4.7-1)
       Bits:           64bit
       Build:          Jul  2 2016 17:42:40 (#default)
       Unicode:        UCS4

    PyVISA Version: 1.8

    Backends:
       ni:
          Version: 1.8 (bundled with PyVISA)
          #1: /usr/lib/x86_64-linux-gnu/libvisa.so.0.0.0:
             found by: auto
             bitness: 64
             Could not get more info:
                VI_ERROR_NSUP_ATTR (-1073807331): The specified attribute is not defined or supported by the referenced object.
       py:
          Version: 0.3.dev0
          ASRL INSTR: Available via PySerial (3.4)
          TCPIP INSTR: Available
          USB RAW: Available via PyUSB (1.0.2). Backend: N/A
          USB INSTR: Available via PyUSB (1.0.2). Backend: N/A
          GPIB INSTR:
             Please install linux-gpib to use this resource type.
             No module named gpib
          TCPIP SOCKET: Available
       sim:
          Version: 0.3
          Spec version: 1.1

** A. The Test**

Step 1. Executed the  below using inst.query_binary_values()

    IP_SG = '10.10.100.131'
    rm = visa.ResourceManager('@py')
    inst = rm.open_resource('TCPIP::'+ IP_SG + '::INSTR')
    inst.timeout = 30000
    print("Session ID : %s" % (inst.session))
    print("Instrument identification information : %s" % (inst.query("*IDN?").rstrip()))
    data = inst.query_binary_values(:MEMory:DATA:IQ? "waveform_file")

Outcome

    Session ID : 1652253
    Instrument identification information : Agilent Technologies, N5182A, MY50140960, A.01.85

The same timeout problem
![image](https://user-images.githubusercontent.com/20521720/36331927-bf6fd764-1324-11e8-85c6-5f366c5b9d2b.png)

Step 2. Executed the  below using inst.query()

    IP_SG = '10.10.100.131'
    rm = visa.ResourceManager('@py')
    inst = rm.open_resource('TCPIP::'+ IP_SG + '::INSTR')
    inst.timeout = 30000
    print("Session ID : %s" % (inst.session))
    print("Instrument identification information : %s" % (inst.query("*IDN?").rstrip()))
    data = inst.query(:MEMory:DATA:IQ? "waveform_file")

Outcome

    Session ID :  8834162
    Instrument identification information : Agilent Technologies, N5182A, MY50140960, A.01.85

The same timeout problem
![image](https://user-images.githubusercontent.com/20521720/36331982-0de62ce0-1325-11e8-9c65-b16e562b0400.png)

Do you need me to do more tests? Meanwhile I will also to continue investigate from my side.

**Comment by MatthieuDartiailh** [comment]
Sorry for the delay, you can try using the latest Pyvisa version to use read_bytes(1) to try reading just a single byte. If this times out I would guess that your instrument either need more time to answer or did not understand your message.

**Comment by svanan77** [comment]
Hi @MatthieuDartiailh ,

I managed to get slot to user the signal generator. 

1. I have uninstalled _pyvisa_ and _pyvisa-py_, then reinstalled both to get the latest version.  I am now using  `PyVISA Version: 1.9.0` .The `python -m visa info` output is below,

![image](https://user-images.githubusercontent.com/20521720/36745832-99196722-1ba5-11e8-8459-ec6ebcbdac6f.png)

2. I have,
a) rerun my original script (as below) to connect to the signal generator to validate all my setup and script are fine. It has executed well at terminal

    IP_SG = '10.10.100.131'
    rm = visa.ResourceManager('@py')
    inst = rm.open_resource('TCPIP::'+ IP_SG + '::INSTR')
    inst.timeout = 10000
    print("\nConnecting to .... %s" % (IP_SG))
    print("Session ID : %s" % (inst.session))
    print("Instrument identification information : %s" % (inst.query("*IDN?").rstrip()))

b) added 	`read_bytes(1)` and my new script looks below,	

    IP_SG = '10.10.100.131'
    rm = visa.ResourceManager('@py')
    inst = rm.open_resource('TCPIP::'+ IP_SG + '::INSTR')
    inst.timeout = 10000
    print("\nConnecting to .... %s" % (IP_SG))
    print("Session ID : %s" % (inst.session))
    print("Instrument identification information : %s" % (inst.query("*IDN?").rstrip()))
    print("SK - Before excuting read_bytes(1)")
    data = self.conn.read_bytes(1)
    print("\nData %s" % (data))
    print ("SK - After excuting read_bytes(1)")

Despite the 10s timeout the excution somehow stopped as despite waiting for 12 minutes, it is still ongoing. The output of both are below,

![image](https://user-images.githubusercontent.com/20521720/36746024-1d32d232-1ba6-11e8-89ac-a4f63e47dbcb.png)

I went ahead to get the `htop` output, as below
![image](https://user-images.githubusercontent.com/20521720/36746801-0fd08bd2-1ba8-11e8-8e51-c82d9c930026.png)

The status is SLEEP, does this mean it is awaiting for a response from the signal generator? This is the same despite 3 times excuting the script.

**Comment by MatthieuDartiailh** [comment]
This is weird. You are using an old version of PyVISA-py.  First think you could do is update to the latest master from github, which includes some improvement as far as timeout are concerned. However to me it looks like either your instrument is very slow (in which case I would suggest to try to sleep manually before calling read bytes), or your command is somehow wrong. To test this you can check the error queue either manually if the instrument has a front panel or querying 'SYST:ERR?' if your instrument supports it (this is a standard SCPI command).

**Comment by svanan77** [comment]
@MatthieuDartiailh 
a) I think I am using the latest version of pyVisa-py. As pyVisa, I had uninstalled pyVisa-py and reinstalled it again using `pip install pyvisa-py`. Is there a way to pull the version info as visa? `python -m pyvisa-py info` did not work. If yes do share it with me, I will provide the info to you.

b) Yes my instrument supports `SYST:ERR?`. There we not errors in the queue, as shown below,
![image](https://user-images.githubusercontent.com/20521720/36749061-822b7934-1bae-11e8-874c-840250de8c22.png)

Will investigate further.

**Comment by MatthieuDartiailh** [comment]
You can install a yet unpublished version directly from github using:
```shell
pip install https://github.com/pyvisa/pyvisa-py/tarball/master
```
A lot has changed since 0.2 !

**Comment by svanan77** [comment]
Sorry my bad.  I have installed from the master and am using the below version

`Version: 0.3.dev0`

Now the output is returning time out for read_bytes(1).

![image](https://user-images.githubusercontent.com/20521720/36750966-b40b8106-1bb3-11e8-95b1-b72712bd042b.png)

Perhaps the instrument dont understand the syntax.

**Comment by MatthieuDartiailh** [comment]
But after sending the command you don't have any error from the instrument ? That is weird. May be worth posting it on the Keysight forum.

**Comment by svanan77** [comment]
@MatthieuDartiailh 

1. I confirm there were no error at the siggen after the timeout due to instr.read_bytes(1) . Will raise this with Keysight 

2. I have changed ':MEM:DATA:IQ? "filename"' to ':MEM:DATA? "filename"' under the advice of Keysight expert. Manage to read the IQ data now though both is usuable syntaxes in the same manual. Would continue to discuss with them why the first one ought to fail when I am using the exact siggen supported by that syntax.

Can I go ahead to close this?

**Comment by MatthieuDartiailh** [comment]
If everything works as expected with the other command I would say yes, since the issue appear to be specific to your instrument and command and not directly related to PyVISA or PyVISA-py.
