### ISSUE TITLE
Remove VISA as a requirement from Readme.md

### ISSUE THREAD

**Issue by ClundXIII** [pyvisa/pyvisa#321]
Hi,

I forced myself onto windows for my latest few experiments. I have been painfully trying to get any proprietary visa library running under linux.

Just to find out that you can use a simple '@py' with pyvisa-py for USB devices. Please make that clear in the docs and the readme to prevent idiots like me from wasting time ;-)

Simon

**Comment by MatthieuDartiailh** [comment]
You are welcome to do a pull request, otherwise I will try to do so as soon as I find some time. Note that the py backend is not totally bugfree. Under linux (Arch), I recently tested the ni-visa AUR package that appears to work (but I gave it only very limited testing).

**Comment by MatthieuDartiailh** [comment]
Closed by #323
