### ISSUE TITLE
Is there any way to query what properties are gettable/settable?

### ISSUE THREAD

**Issue by littlebrat** [pyvisa/pyvisa#333]
What I am thinking would be a query which would output a dictionary-like output with the tree of properties. I understand that the manufacturers are responsible for doing that, but I wanted to know if there is a standard practice for obtaining this information apart from reading the device manual.

**Comment by MatthieuDartiailh** [comment]
Some instruments implement `:SYST:HELP:HEAD?` that gives you all the SCPI commands it supports, but it is rarely implemented from my experience. So no there is no better way than crawling the manual.
