### ISSUE TITLE
pyvisa-py as fallback implementation

### ISSUE THREAD

**Issue by bilderbuchi** [pyvisa/pyvisa#334]
To use pyvisa, one needs a backend, by default the NI-VISA library. Unfortunately, the binary nowadays seems to be behind a [login wall](http://lumen.ni.com/nicif/US/GB_NIDU/content.xhtml?du=http://www.ni.com/download/ni-visa-5.4.1/4626/en/), so there is definitely a barrier to get going.

If no NI-VISA library is found installed, I think it would make sense to automatically fall back to the open [pyvisa-py](https://github.com/pyvisa/pyvisa-py) implementation. This way, nothing changes for users having NI-VISA installed, and it's still used by default if people can install the library, but the procedure is smoother than now for people who don't have access to that library.

In particular, it would make it easier to use packages like pymeasure where you are [not necessarily using](http://pymeasure.readthedocs.io/en/latest/tutorial/connecting.html) a `ResourceManager` to configure the backend choice. Yes I know that it's possible to select the backend via environment variable, but that's another extra step that users have to do every time they use pyvisa.

Does the proposal to automatically fall back to pyvisa-py if NI-VISA is not installed sound good/smart/acceptable?

**Comment by MatthieuDartiailh** [comment]
I believe it would make sense yes to use pyvisa-py as a fallback backend. I have no time to do myself at the time being but I will be happy to review and merge a PR in that direction.

**Comment by bilderbuchi** [comment]
Ok, do you have any pointers/tips where to start and how to approach implementing this?

**Comment by MatthieuDartiailh** [comment]
The function that needs to be updated is open_visa_library in highlevel.py
You could wrap the library instantiation and decide to fall back if an error occurs.

**Comment by bilderbuchi** [comment]
Thanks, I'll see what I can do. :-)
