### ISSUE TITLE
Error for USBInstrument

### ISSUE THREAD

**Issue by verysure** [pyvisa/pyvisa#352]
https://github.com/pyvisa/pyvisa/blob/7d8c059dbf25d88f358dd45c1290ad13ff80eb07/pyvisa/resources/usb.py#L57

Dear developers,

I was using USBInstrument for my usb connections. However, I found out that there is a missing `self.session` as the first argument for `usb_control_out`. Also, the naming convention is a little bit weird, `control_in` vs `usb_control_out`.

Should I issue a pull request for a fix and a possible naming change?

Thanks,
- verysure

**Comment by MatthieuDartiailh** [comment]
Your are welcome to open a PR to fix the missing argument and also make the naming more homogeneous (`control_out`). You could also add a `usb_control_out` emitting a `FutureWarning` and calling `control_out`. And add a mention of the change in the CHANGES file.
