### ISSUE TITLE
Making the methods in pyvisa.util available to the end user

### ISSUE THREAD

**Issue by marccheneau** [pyvisa/pyvisa#366]
I find myself using some of the methods defined in `pyvisa.util`. Could this submodule be automatically loaded by `import visa`?

**Comment by MatthieuDartiailh** [comment]
You can `import pyvisa.util`. visa is just a shorthand meant for the most standard cases but it is fine to directly import from pyvisa if you need more (util, constants, etc). Feel free to re-open if you consider this requires a more in depth debate.
