### ISSUE TITLE
Trouble passing string variable to AG34970a and gp-switch card.

### ISSUE THREAD

**Issue by czeck6** [pyvisa/pyvisa#368]
I'm trying to control a gp-switch card in slot three of an AG34970a using pyvisa.

When I enter this in the console.

```
>>>dac.write("ROUTe:CLOSe (@301,302,303,304,305,306,307,308)")
```

the switch functions normally and quietly closes the appropriate switches. The console outputs

(48L, <StatusCode.success: 0))

my device is named dac.

but when I try to use a string variable instead the response in the console is the same but the instrument beeps and does not close the switches. The error code on the device is error 103 which I believe means an invalid separator but since one works I don't understand why the other wouldn't.

```
>>>print(switch_str)
'"ROUTe:CLOSe (@301,302,303,304,305,306,307,308)"'
>>>dac.write(switch_str)
(48L, <StatusCode.success: 0))  

```
People keep guessing that it's the double quotes but my decision to include the quotes in the string by using the single quote outside the double quote is that the string passed to the device within the parenthesis seems to need be surrounded by double quotes.  If I don't include them python simply does a syntax error.

Is it not possible to use a variable in conjunction with the .write command?

My variable switch_str is actually a concatenation of a couple other parts so I might try doing the concatenation right in the dac.write() part just in case but if anyone has any ideas let me know.  I'll attach the full script if anyone wants to see.  My style is ugly I know so be prepared.  It is for balancing cell voltages in a battery and I know it has other problems, this is just the one that i'm working on right now.

[balancer.txt](https://github.com/pyvisa/pyvisa/files/2453994/balancer.txt)

I figured it out. Well sort of. Whatever was going wrong was happening when I was concatenating my string before passing it to the device. I ended up being more explicit with the parts of the write command which were going to remain constant and only passing in the list of channels to close. I'm still not sure why it wasn't working before but it is now.  So maybe it's not an issue.  Just me doing something wrong.
```

fields = ['301', '302', '303', '304', '305', '306', '307']

voltage = dac.query_ascii_values('MEAS:VOLT:DC? AUTO,DEF,(@101:107)')
               #convert the resulting voltage values into floats
    flvolts=[float(i) for i in voltage]
               #create a dictionary with the fields and corresponding voltage values
     dictionary=dict(zip(fields, flvolts))
               #evaluate the voltage list to determine the lowest value
     minval = min(flvolts)
               #produce a list of gp-switch channels that need to be closed to get cells balanced
               #targetval was created further up.  initially it is the same as minval but minval can
               #change.  Targetval shouldn’t
     switch_list=({k for (k,v) in dictionary.items() if v >= targetval})
               #begin generating the string to be sent to the device by converting the floats to strings
     str_list=[str(i) for i in switch_list]
               #Set up an empty list
     formatted_str_list=""
               #Format str_list into a string of comma separated numbers.
     for i in str_list:
          formatted_str_list += str(i) + ","     
               #instruct the device to close the channels that need drained
               #because they are higher than the minval
     dac.write("ROUTe:CLOSe (@" + formatted_str_list + "308)")

```

**Comment by MatthieuDartiailh** [comment]
I believe  your issue was the following line:
```python
switch_str='"ROUTe:CLOSe (@' + formatted_str_list + '308)"'
```
which created a string with `"` inside while you probably wanted:
```python
switch_str= "ROUTe:CLOSe (@" + formatted_str_list + "308)"
```
Also noted that to build `formatted_str_list` you could have used `", ".join(str_list)` to avoid the explicit for loop.

**Comment by czeck6** [comment]
Thank you.  Yes, that's exactly what I ended up doing.  I just needed some sleep to see what was wrong.  It's funny how much that helps.  I didn't know the join thing.  I'm still very much a newb.  I appreciate your advice.
