### ISSUE TITLE
time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8

### ISSUE THREAD

**Issue by bjaraujo** [pyvisa/pyvisa#394]
..C:\Users\bjaraujo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyvisa\resources\gpib.py:101: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  starting_time = time.clock()
C:\Users\bjaraujo\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyvisa\resources\gpib.py:107: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  adjusted_timeout = int((starting_time + timeout/1e3 - time.clock())*1e3)
  
>python -m visa info

```
Machine Details:
   Platform ID:    Windows-10-10.0.16299-SP0
   Processor:      Intel64 Family 6 Model 78 Stepping 3, GenuineIntel

Python:
   Implementation: CPython
   Executable:     C:\Users\bjaraujo\AppData\Local\Programs\Python\Python37-32\python.exe
   Version:        3.7.2
   Compiler:       MSC v.1916 32 bit (Intel)
   Bits:           32bit
   Build:          Dec 23 2018 22:20:52 (#tags/v3.7.2:9a3ffc0492)
   Unicode:        UCS4

PyVISA Version: 1.9.1

Backends:
   ni:
      Version: 1.9.1 (bundled with PyVISA)
      #1: C:\WINDOWS\system32\visa32.dll:
         found by: auto
         bitness: 32
         Vendor: National Instruments
         Impl. Version: 17827072
         Spec. Version: 5244928
```

**Comment by MatthieuDartiailh** [comment]
Thanks for the report.

**Comment by tirkarthi** [comment]
`time.clock` is now removed in 3.8 : https://github.com/python/cpython/pull/13270/

**Comment by MatthieuDartiailh** [comment]
Thanks for the update @tirkarthi. I f anybody is willing to make a PR, it will be welcome.

**Comment by tirkarthi** [comment]
I can find two places as in the original report in gpib.py. Since the project supports Python 2 which doesn't have process_time or perf_counter one solution would be to try `time.process_time` and to fallback to `time.clock` in case of `AttributeError`.

```python
try:
    clock = time.process_time
except AttributeError:
    clock = time.clock
```

**Comment by MatthieuDartiailh** [comment]
We have a compat package file and this kind of version handling could be done in its \_\_init\_\_.py, so as to avoid duplicating this in multiple places.
