### ISSUE TITLE
highlevel.open_resource return type too abstract

### ISSUE THREAD

**Issue by gasparka** [pyvisa/pyvisa#405]
Documented return type is `pyvisa.resources.Resource`, which is missing popular functions like `query`, `write` etc.. This leads IDEs to report mistakes in correct code:
![Screenshot_2019-04-01_18-29-22](https://user-images.githubusercontent.com/16946258/55339327-1f226780-54ab-11e9-97cf-f45ea397462e.png)
Error: Unresolved attribute reference 'query' for class 'Resource' 

Current workaround is to annotate the type manually:
```Python
from pyvisa.resources import TCPIPInstrument
inst: TCPIPInstrument = rm.open_resource("TCPIP::192.168.1.245")
```
This also gives you the appropriate IntelliSense. Now, it would be nice if PyVisa would handle this by default, but looks like the class hierarchy is quite complex. Ideas?

**Comment by MatthieuDartiailh** [comment]
The issue here is that depending on the resource name you can get very different results (including PXI interfaces that do not have read/write/query). I am not sure we can do much better. Manually annotating because you know what kind of resource to expect seems reasonable to me.

**Comment by gasparka** [comment]
I agree. Thanks.
