### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by slightlynybbled** [pyvisa/pyvisa#408]
Under `FAQ`, and `Which libraries are used by PyVISA-py`, the links for each of the projects pyserial and pyusb are both broken.

https://pyvisa-py.readthedocs.io/en/latest/#which-libraries-are-used-by-pyvisa-py

Link to pyserial: https://pythonhosted.org/pyserial/

Link to pyusb: https://github.com/pyusb/pyusb

**Comment by MatthieuDartiailh** [comment]
Thanks for the report, I will fix it Wednesday evening. If you want to submit a PR feel free to do so.

**Comment by slightlynybbled** [comment]
Gaa!  Meant to submit to project [pyvisa-py](https://pyvisa-py.readthedocs.io/en/latest/#).  Please ignore!

**Comment by MatthieuDartiailh** [comment]
Don't worry I figured it out.

**Comment by MatthieuDartiailh** [comment]
And I am a maintainer for both.
