### ISSUE TITLE
In DashDAQ, VI_ERROR_RSRC_BUSY (-1073807246): The resource is valid, but VISA cannot currently access it.

### ISSUE THREAD

**Issue by hududed** [pyvisa/pyvisa#411]
Hi

not sure which is responsible for this error, DashDAQ or pyVISA. But I am trying to establish a serial communication (RS232) with VISA on windows 10, python 3.7.3, and trying to run this with Dash DAQ [https://github.com/plotly/dash-daq](url)

```import dash
import visa

rm = visa.ResourceManager()
instr = rm.open_resource('ASRL1::INSTR')

app = dash.Dash(__name__)
server = app.server
app.scripts.config.serve_locally = True
app.config["suppress_callback_exceptions"] = True

if __name__ == '__main__':
    # defaultset()
    app.run_server(port=8800, debug=True)
```

but get the following error when it's trying to open the resource.

`pyvisa.errors.VisaIOError: VI_ERROR_RSRC_BUSY (-1073807246): The resource is valid, but VISA cannot currently access it.`

Running this serial connection independent of dash daq server works fine. Running this with a GPIB connection to the ESP300 instrument module from pymeasure seems to also work fine [https://github.com/ralph-group/pymeasure](url)

Has anyone given this serial connection with DashDAQ a try? What seems to be problem here?

Cheers, H

**Comment by MatthieuDartiailh** [comment]
As mentioned in #512 I believe the issue is that somehow when running the server the connection to the instrument is opened twice which is not supported for serial instrument. I do not know enough the internals of dash to provide a workaround. Please use #512 for any new report.
