### ISSUE TITLE
Logging in __del__ causes issues since Python 3.4

### ISSUE THREAD

**Issue by cpu20** [pyvisa/pyvisa#416]
When using logging to a file, in a script that uses PyVisa, below exceptions occur:

> Agilent Technologies,33220A,2.00-2.00-22-2
>
> Exception ignored in: <function Resource.__del__ at 0x034F1FA8>
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyvisa\resources\resource.py", line > 108, in __del__
>   File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyvisa\resources\resource.py", line > 242, in close
>   File "C:\Program Files (x86)\Python37-32\lib\logging\__init__.py", line 1371, in debug
>   File "C:\Program Files (x86)\Python37-32\lib\logging\__init__.py", line 1519, in _log
>   File "C:\Program Files (x86)\Python37-32\lib\logging\__init__.py", line 1529, in handle
>   File "C:\Program Files (x86)\Python37-32\lib\logging\__init__.py", line 1591, in callHandlers
>   File "C:\Program Files (x86)\Python37-32\lib\logging\__init__.py", line 905, in handle
>   File "C:\Program Files (x86)\Python37-32\lib\logging\__init__.py", line 1131, in emit
>   File "C:\Program Files (x86)\Python37-32\lib\logging\__init__.py", line 1121, in _open
>   File "C:\Program Files (x86)\Python37-32\lib\_bootlocale.py", line 12, in getpreferredencoding
> AttributeError: 'NoneType' object has no attribute 'utf8_mode'
> Exception ignored in: <function ResourceManager.__del__ at 0x034D5C00>
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyvisa\highlevel.py", line 1564, in > __del__
>   File "C:\Program Files (x86)\Python37-32\lib\site-packages\pyvisa\highlevel.py", line 1585, in > close
>   File "C:\Program Files (x86)\Python37-32\lib\logging\__init__.py", line 1371, in debug
>   File "C:\Program Files (x86)\Python37-32\lib\logging\__init__.py", line 1519, in _log
>   File "C:\Program Files (x86)\Python37-32\lib\logging\__init__.py", line 1529, in handle
>   File "C:\Program Files (x86)\Python37-32\lib\logging\__init__.py", line 1591, in callHandlers
>   File "C:\Program Files (x86)\Python37-32\lib\logging\__init__.py", line 905, in handle
>   File "C:\Program Files (x86)\Python37-32\lib\logging\__init__.py", line 1131, in emit
>   File "C:\Program Files (x86)\Python37-32\lib\logging\__init__.py", line 1121, in _open
> NameError: name 'open' is not defined

The script used to generate these exceptions:

```python
#Encoding: utf-8

import visa, logging

if __name__ == "__main__":
     # Logging to a file causes NameError: name 'open' is not defined
     logging.basicConfig(filename="debug.log", level=logging.DEBUG)
     logging.debug("Debug message")

     rm = visa.ResourceManager()
     res = rm.list_resources()

     inst = rm.open_resource(res[0])
     print(inst.query("*IDN?"))
```

These exceptions occur when logging to a file and when using Python >3.4. This is because since Python 3.4, open() is no longer available in the destructor which causes the "NameError: name 'open' is not defined". (See: https://bugs.python.org/issue26789)

A possible solution for this issue is to use atexit to execute the close() methods. I have tested this approach and it works as expected.

**Comment by MatthieuDartiailh** [comment]
Thanks for the report. However I do not see a quick and perfect solution.
Delaying till atexit for closing resources would mean that resources are kept open far longer than they should (since atexit itself would keep them alive), so I am against this solution. 
The Python issue you reference suggests a reasonable (although imperfect) solution which is to call `logging.shutdown`.
One thing we could do to improve the situation would be to call `close` in `__del__` conditionally on the fact that the resource has not already been closed. This way in a normal use of pyvisa only the resource manager would possibly raise and fixing it would be a simple matter of closing it manually.

Note that in a script it is recommended to use a context manager when opening resources, to make sure the resource is properly closed.

**Comment by cpu20** [comment]
> One thing we could do to improve the situation would be to call close in __del__ conditionally on the fact that the resource has not already been closed. This way in a normal use of pyvisa only the resource manager would possibly raise and fixing it would be a simple matter of closing it manually.

I don't see how that would fix the issue. As long as there is logging in the destructor the errors will occur.

**Comment by MatthieuDartiailh** [comment]
The logging happens in `close` which is called in `__del__` so avoiding closing an already closed resource will avoid spurious errors since we won't call `close` but will not eliminate errors coming from unclosed resources obviously.

**Comment by MatthieuDartiailh** [comment]
This issue can only occur during interpreter shutdown and with #424 it should not occur if all resources have been properly closed before exiting the Python application. Feel free to reopen if necessary.
