### ISSUE TITLE
 pyVISA - GPIB - reading binary data fails

### ISSUE THREAD

**Issue by xyTo** [pyvisa/pyvisa#43]
Hi,

I am using pyVISA v1.4 on python 2.7.x.
I am trying to read data in binary form an HP Network analyzer.

Reading in ASCII-form works fine but is very slow. THowever, turning the device into 64-bit binary mode trips an error.

I tried the following:
my_instrument = instrument("GPIB0::11", values_format = double)

this triggers the following error:

---

File "C:\Python27\lib\site-packages\pyvisa\visa.py", line 463, in read_values
raise InvalidBinaryFormat
pyvisa.visa_exceptions.InvalidBinaryFormat: unrecognized binary data format

---

Any suggestion on how to get to the core of this problem?

Thanks for your help!

**Comment by zamora18** [comment]
Hello, I know this thread is old, but I am attempting to communicate with an HP Network Analyzer using pyVISA and am running into some issues. @xyTo it seems that you were working on a similar project. Would you be willing to send me a copy of your script that initializes communication to the instrument? As of now I receive an error "_Insufficient location information or the requested device or resource is not present in the system._" Thank you very much.

**Comment by dvincentwest** [comment]
Check out scikit-rf

**Comment by dvincentwest** [comment]
Sorry I sent the comment prematurely. Scikit-rf has a virtual instrument classes implementing communication apis for mondern network analyzers based on Pyvisa and using SCPI for the direct commands. Your model may be old and have different scpi commands but the patterns should all be the same

**Comment by MatthieuDartiailh** [comment]
@zamora18 could you please send us more details on your setup (output of `python -m visa info`) and the connection string you used to access your instrument. If possible I would suggest to see if you can find your device in the ones listed by the `list_resources` method of the resource manager, or in an external tool such as NiMAX.

**Comment by zamora18** [comment]
Thank you for the quick response. I noticed that I was running a 64-bit python, so I installed a 32-bit version but I am still getting the same problem. I am not sure what path to the library to add as the argument for ResourceManager() (I have read that it can help in finding the pyvisa library). I am also using PyCharm, and have the interpreter using the correct 32-bit version of python, but also get the same errors. 

I have not been able to get past the initialization of the instrument:
```python
import visa
rm = visa.ResourceManager()
```
Returns the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda2_32/lib/python2.7/site-packages/pyvisa/highlevel.py", line 1488, in __new__
    visa_library = open_visa_library(visa_library)
  File "/home/ubuntu/anaconda2_32/lib/python2.7/site-packages/pyvisa/highlevel.py", line 1460, in open_visa_library
    return cls(argument)
  File "/home/ubuntu/anaconda2_32/lib/python2.7/site-packages/pyvisa/highlevel.py", line 96, in __new__
    raise OSError('Could not open VISA library:\n' + '\n'.join(errs))
OSError: Could not open VISA library:
```

The output of python -m visa info:
```
Machine Details:
   Platform ID:    Linux-4.4.0-92-generic-x86_64-with-debian-stretch-sid
   Processor:      x86_64

Python:
   Implementation: CPython
   Executable:     /home/ubuntu/anaconda2_32/bin/python
   Version:        2.7.14
   Compiler:       GCC 7.2.0
   Bits:           32bit
   Build:          Oct 16 2017 17:53:52 (#default)
   Unicode:        UCS4

PyVISA Version: 1.8

Backends:
   ni:
      Version: 1.8 (bundled with PyVISA)
      Binary library: Not found
```

@dvincentwest I will look into Scikit-rf. Thank you.

**Comment by MatthieuDartiailh** [comment]
You can use either 64 or 32 bits. The problem is that pyvisa is a wrapper for the VISA library, which you need to install separatly. Alternatively, you can install, in addition to pyvisa, pyvisa-py which provides a pure Python backend. To use it you can create the resouce manager as follow: `ResourceManager ('@py')`.

**Comment by zamora18** [comment]
I may have been reading old threads that mentioned it has to be 32-bit python. However on the [NI VISA documentation](http://pyvisa.readthedocs.io/en/stable/getting_nivisa.html#getting-nivisa) for installing on Linux machines it states: ```Currently, only 32-bit applications are supported on the x86-64 architecture```. Is this correct? I have installed the NI VISA backend already, and I believe it is configured. However, the output from python -m info visa shows ```Binary library: Not found```. Is this a problem?
I will include the output after switching back to 64 bit, and installing pyvisa-py:
```
Machine Details:
   Platform ID:    Linux-4.4.0-92-generic-x86_64-with-Ubuntu-16.04-xenial
   Processor:      x86_64

Python:
   Implementation: CPython
   Executable:     /usr/bin/python
   Version:        2.7.12
   Compiler:       GCC 5.4.0 20160609
   Bits:           64bit
   Build:          Nov 19 2016 06:48:10 (#default)
   Unicode:        UCS4

PyVISA Version: 1.8

Backends:
   ni:
      Version: 1.8 (bundled with PyVISA)
      Binary library: Not found
   py:
      Version: 0.2
      ASRL INSTR: Available via PySerial (3.0.1)
      TCPIP INSTR: Available 
      USB RAW: Available via PyUSB (1.0.2). Backend: libusb1
      USB INSTR: Available via PyUSB (1.0.2). Backend: libusb1
      GPIB INSTR: Available 
      TCPIP SOCKET: Available
```
I have downloaded the drivers for the GPIB interface, and run this simple script:
```python
import visa

rm = visa.ResourceManager('@py')

rm.list_resources()
```
There seems to be an error with the listener:
```
Traceback (most recent call last):
  File "/home/ubuntu/vna_comm_test/hello_world.py", line 5, in <module>
    rm.list_resources()
  File "/usr/local/lib/python2.7/dist-packages/pyvisa/highlevel.py", line 1560, in list_resources
    return self.visalib.list_resources(self.session, query)
  File "/usr/local/lib/python2.7/dist-packages/pyvisa-py/highlevel.py", line 231, in list_resources
    for key, st in sessions.Session.iter_valid_session_classes()], [])
  File "/usr/local/lib/python2.7/dist-packages/pyvisa-py/gpib.py", line 57, in list_resources
    return ['GPIB0::%d::INSTR' % pad for pad in _find_listeners()]
  File "/usr/local/lib/python2.7/dist-packages/pyvisa-py/gpib.py", line 35, in _find_listeners
    if gpib.listener(BOARD, i) and gpib.ask(BOARD, 1) != i:
gpib.GpibError: listener() failed: An attempt to write command bytes to the bus has timed out.

Process finished with exit code 1
```

**Comment by zamora18** [comment]
I think I may have found my problem. 
The NI-VISA installation was not successful (although it actually says at the end of the installation script that it **was**) because rpm was not found since I am running on Ubuntu. This is the output from the installation:
```
*****************************************************************************
  NI-VISA for Linux
     version 5.4.1f0 for Linux
*****************************************************************************

National Instruments products support the following Linux distributions:
   openSUSE
   Red Hat Enterprise Linux Desktop + Workstation
   Scientific Linux
Refer to README.txt for the latest information at the time of release.
Refer to www.ni.com/linux for the most recent information about Linux
support at National Instruments.

Continue? [Yn] 

Checking required install tools...
Checking installer tool versions...
rpm        Not found in current path
tar        1.28
Checking dependencies...
glibc      2.23 
Unpacking install files to /tmp/nivisa-5.4.1f0.install...

NATIONAL INSTRUMENTS SOFTWARE LICENSE AGREEMENT (LINUX DRIVER SOFTWARE)
...
...
...
(c) 2004-2011 National Instruments Corporation. All Rights Reserved.
371460B-01
May 2011

By installing this software, you are acknowledging acceptance of the terms
of the included license file (LICENSE.txt). 

Do you accept the license? [ynq] y

NI-VISA for Linux version 5.4.1f0
is about to be installed using rpm at /usr/local/natinst

./INSTALL: line 1515: -q: command not found

Would you like to continue? [Yn] Y

Installing NI-VISA for Linux version 5.4.1f0...
Pre Installation .
Post Installation .
./INSTALL: line 419: --showrc: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
./INSTALL: line 667: -qp: command not found
Pre Installation ...................................
Post Installation ...................................

FOR PATENTS COVERING NATIONAL INSTRUMENTS PRODUCTS, REFER TO
THE PATENTS.txt FILE ON /home/jacob/fortem/temp_mount AND/OR
www.ni.com/patents

NI-VISA for Linux Installation completed successfully.
```

Are you familiar with this problem? After some reading I believe there are some work-arounds for rpm installation on Ubuntu using alien. Do you have any suggestions?

**Comment by MatthieuDartiailh** [comment]
I must say I have no experience in trying to get Ni-VISA to work on Ubuntu, so I cannot help with that. As far as the error with the '@py' backend is concerned, as it is occurs at a very low-level you may consider updating/re-installing your GPIB drivers and linux-gpib. Alternatively you could try using https://github.com/tivek/gpib_ctypes which is a recent binder for gpib drivers. Look at this thread for more details https://github.com/pyvisa/pyvisa-py/issues/105.
