### ISSUE TITLE
Rohde&Schwarz, HMC8015 bytes reading 

### ISSUE THREAD

**Issue by ApollineChappard** [pyvisa/pyvisa#434]
Hello,

I want to read the data from my Rohde&Schwarz, HMC8015 using following code:

```
rm = visa.ResourceManager()
name = rm.list_resources()
print(name)


bytes is str

#using with allows to close explicitly the resource at the end of the script
with rm.open_resource('ASRL3::INSTR') as Power_Analyser:
		
	print(Power_Analyser.query('*IDN?'))
	print(Power_Analyser)


	Power_Analyser.timeout = 2500 #2,5 seconds
	Power_Analyser.write_termination = '\n'

	#read the variables of the instrument
	Power_Analyser.write("CHANnel1:MEASurement1:DATA?")
	Data = Power_Analyser.read_raw()
	
	var_1 = float(Data[0:10])
	var_2 = float(Data[11:21])
	var_3 = float(Data[22:33])
	var_4 = float(Data[34:44])
	var_5 = float(Data[45:55])
	var_6 = float(Data[56:66])
	var_7 = float(Data[67:77])
	var_8 = float(Data[78:88])
	var_9 = float(Data[89:99])
	
	Daten_float = [var_1, var_2,  var_3, var_4, var_5, var_6, var_7, var_8, var_9]

	print('Daten_float =', Daten_float)
```

Which works fine, and gives me the values in float in the list Daten_float:

`Daten_float = [233.47, 0.001509, -7.5002, 49.994, 300.0, 10.0, 0.35231, 0.34423, 0.21289]`.

My question is: is there any documentation which says which bytes correspond to what ? I could not found any information about this on my device manual ([here](https://scdn.rohde-schwarz.com/ur/pws/dl_downloads/dl_common_library/dl_manuals/gb_1/h/hmc80115/HMC8015_SCPImanual_en_01.pdf)), on Python visa manual or anywhere else. This would be very helpful, because I don't know what I get.

**Comment by MatthieuDartiailh** [comment]
According to your instrument manual the command return one of the following quantity depending on the value reported by `CHAN<n>:MEAS:FUNC?`:
P Active power P (Watt)
S Apparent power S (VA)
Q Reactive power Q (var)
LAMBda Power factor λ (PF)
PHI Phase difference Φ ( ° )

You get 6 or 10 values depending on the page size you selected. The values correspond to the cells of the page. The type of quantity reported is independent of the type you selected for the display.

Please note that I never used that instrument and I am just reading the manual. For any further and similar questions, specific to the instrument working and unrelated to PyVISA, please contact the manufacturer.
