### ISSUE TITLE
Mark and Space 

### ISSUE THREAD

**Issue by cah-sachin** [pyvisa/pyvisa#445]
Hi,

We have legacy device which uses Mark and Space strategy to read the data from port. Here is a small snippet of code.

    def Write(self, raw_data):
        self.msg_data = raw_data
        self.msg_read_cntr = 0
        self.msg_delay_time = time.time()
        delay = raw_data["delay_in_sec"]
        poll_data = raw_data["data"]
        if raw_data["type"] == "BROADCAST":
            logger.critical("raw data type BROADCAST")
            logger.critical(raw_data)
            self.serial_port.parity=serial.PARITY_MARK
            self.serial_port.rtscts=0
            logger.critical(delay)
            sleep(delay)
            logger.critical("Writing into port")
            logger.critical(poll_data)
            logger.critical(poll_data.decode('hex'))
            logger.critical(bytearray(poll_data.decode('hex')))
            self.serial_port.write(bytearray(poll_data.decode('hex')))
            sleep(delay)
            self.serial_port.parity=serial.PARITY_SPACE
            self.serial_port.rtscts=1
            sleep(delay)
        else:
            logger.critical(raw_data)
            header=bytearray(b'\x04')
            self.serial_port.parity=serial.PARITY_MARK
            self.serial_port.rtscts=0
            sleep(delay)
            self.serial_port.write(header)
            sleep(delay)
            logger.critical("header")
            logger.critical(header)
            self.serial_port.write(header)
            sleep(delay)
            self.serial_port.parity=serial.PARITY_SPACE
            sleep(delay)
            logger.critical(poll_data)
            logger.critical(poll_data.decode('hex'))
            logger.critical(bytearray(poll_data.decode('hex')))
            self.serial_port.write(bytearray(poll_data.decode('hex')))
            sleep(delay)
            self.serial_port.rtscts=1
            sleep(delay)

        def Read(self):
        ret = ""
        if not self.serial_port or not self.serial_port.isOpen():
            return None
        if (self.serial_port.inWaiting() == 0):
            if (time.time() >= (self.msg_delay_time + 10)) and (self.msg_read_cntr == 0):
                logger.critical("============MSG DATA==============")
                logger.critical(self.msg_data)
                logger.critical("============MSG DATA==============")
                self.Write(self.msg_data)
            return None
        else:
            self.msg_read_cntr += self.serial_port.inWaiting()
        while self.serial_port.inWaiting() > 0:
            ret += self.serial_port.read(1)
        sleep(0.1)
        return ret

How we can achieve above using visa library ?

**Comment by MatthieuDartiailh** [comment]
I am not a specialist in the low level implementation of the VISA protocol on serial resources but it does not seem to have any built-in support for MARK and SPACE strategy. You can change the parity of a serial resource using:
```python
from pyvisa import constants 
resource.set_attribute(constants.VI_ATTR_ASRL_PARITY, constants.Parity.mark)
```
However it won't be natural and it may be better to simply stick with pyserial, since the instrument does not seem to use the VISA protocol.
