### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by thinker5112** [pyvisa/pyvisa#472]
When I have successfully installed the pyvisa, it is showing that ModuleNotFoundError : No module named pyvisa.
![Screenshot (99)](https://user-images.githubusercontent.com/57936299/69124488-06ae9e00-0aca-11ea-9f22-734b86724fc9.png)

**Comment by MatthieuDartiailh** [comment]
I am not familiar with pycharm but did you check you installed pyvisa in the right environment ?

**Comment by thinker5112** [comment]
Yes I have checked it. And it was installed in the right environment.

Regards,
S. D. Pavan Kumar
Member Technical Engineer,
HCL Technologies Ltd.
________________________________

**Comment by MatthieuDartiailh** [comment]
How did you install pyvisa and how did you check ?

**Comment by MatthieuDartiailh** [comment]
Closing for lack of feedback feel free to reopen if necessary.
