### ISSUE TITLE
What are Read/Write Requirements for standard Serial Devices?

### ISSUE THREAD

**Issue by lucasgcb** [pyvisa/pyvisa#475]
Hello,

Thank you for this library first of all, I've been using PyVisa to command and set a HAMEG HMS-X (Spectrum Analyzer) instrument and it has been working perfectly. Currently I just have a _not critical_ problem that I need help circumventing if possible.

The situation is the following: 

I have the instrument connected to my serial interface working fine, and also a microcontroller connected to my serial interface that executes some operations in my measuring environment in parallel. The instrument interfaces with PyVisa and the microcontroller with PySerial currently.

I've noticed PyVisa actually picks up my Microcontroller as a resource, I can even open it and a hold a session. However, it seems moot as it fails to use `write_raw()` to input my serial commands on it (one of them is `*IDN?`, "identical" to the real instrument). It also times out when reading from it. 

The way I do it currently is: I try opening and querying the resources with PyVisa, then close and open in PySerial the one that times out; this consumes some startup time and looks very hacky.

How can I make it so my serial-connected microcontroller can communicate through the PyVisa wrapping, taken it works through PySerial just fine and can be detected by PyVisa?

**Comment by MatthieuDartiailh** [comment]
I am not sure where to find the actual specification. @hgrecco may know  but you can have a look at how pyvisa-py interact with serial resources for a first idea. You can also have a look at http://www.ivifoundation.org/downloads/Class%20Specifications/vpp43_2017-10-17.pdf and more specifically at the attributes for ASRL resources that control data transfer.
