### ISSUE TITLE
write_raw returns a tuple

### ISSUE THREAD

**Issue by pigrew** [pyvisa/pyvisa#476]
The documentation comment of `MessageBasedInterface.write_raw` says it returns `int`, but it actually returns `Tuple[int,pyvisa.constants.StatusCode]`.

Could the documentation be updated to show it returning a tuple (since that's what `visalib.write(...)` returns)?

Thanks!

**Comment by MatthieuDartiailh** [comment]
Returning a tuple does not line with the other methods of MessageBasedResource (including other write method). To me the current situation is a bug and the code not the documentation needs to be updated.

It will be backward incompatible but checking the number of characters written is not generally needed so hopefully it will only affect few people.

**Comment by MatthieuDartiailh** [comment]
This is now fixed on master.
