### ISSUE TITLE
Problem configuring PyVisa with USB device

### ISSUE THREAD

**Issue by lplPerard** [pyvisa/pyvisa#478]
Hello all,

I am trying to implement PyVisa in a code to pilot a Keythley 2450 Sourcemeter. I know everything works fine on my computer since I generally pilot my instrument via Matlab.

When I execute `python -m visa info` I get the following result

`Machine Details:
   Platform ID:    Windows-10-10.0.18362-SP0
   Processor:      Intel64 Family 6 Model 158 Stepping 10, GenuineIntel

Python:
   Implementation: CPython
   Executable:     C:\Users\perardl\AppData\Local\Programs\Python\Python38-32\python.exe
   Version:        3.8.0
   Compiler:       MSC v.1916 32 bit (Intel)
   Bits:           32bit
   Build:          Oct 14 2019 19:21:23 (#tags/v3.8.0:fa919fd)
   Unicode:        UCS4

PyVISA Version: 1.10.1

Backends:
   ni:
      Version: 1.10.1 (bundled with PyVISA)
      #1: C:\Windows\system32\visa32.dll:
         found by: auto
         bitness: 32
         Vendor: National Instruments
         Impl. Version: 19923456
         Spec. Version: 5244928
   py:
      Version: 0.3.1
      ASRL INSTR: Available via PySerial (3.4)
      USB INSTR: Available via PyUSB (1.0.2). Backend: N/A
      USB RAW: Available via PyUSB (1.0.2). Backend: N/A
      TCPIP INSTR: Available
      TCPIP SOCKET: Available
      GPIB INSTR:
         Please install linux-gpib to use this resource type.
         No module named 'gpib'`

The backend for USB is not found, but libusb is installed on my machine.

I am lost, can someone help ?

**Comment by MatthieuDartiailh** [comment]
Since you are on Windows and have NI Visa installed I would not try using pyvisa-py that is less stable, in which case you can ignore the second part of the report.
