### ISSUE TITLE
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

### ISSUE THREAD

**Issue by mra7072** [pyvisa/pyvisa#487]
Ran this setup code on a windows 10 machine with NI VISA library with a Agilent 34401A multimer. It worked fine, i was also able to take a measurement. However, I've migrated to a raspberry pi 4 with Rasbian buster loaded. Since, NI-VISA is not supported, I'm using the Pyvisa-py as the backend. Now, when executing this setup code, I'm getting a timeout issue. I've listed the code below. Is the Pyvisa-py backend insufficient? Because the only differences I see is the difference in OS from windows 10 to raspbian and the difference in the backend due to this migration. 

def setup():
        rm=pyvisa.ResourceManager()
        resources = rm.list_resources()
        print(resources)
        print(rm)
        if resources == None:
            print("No connected devices found")
    
        DMM = rm.open_resource(resources[0],
            baud_rate=9600, data_bits=8, flow_control=4,
            parity = Parity.none,stop_bits=StopBits.two)

        #clear buffers
       
        #set read/write terminators to dictate end of command"
        DMM.read_termination = '\n'
        DMM.write_termination = '\n'
        DMM.write("*rst; status:preset; *cls")
        #Enable remote mode to interface with multimeter
          DMM.write("SYST:REM")
        #DMM.write("*IDN?")

        print("Connection Established with " + DMM.read())
        return DMM

**Comment by MatthieuDartiailh** [comment]
You can try using the pyvisa-py backend on your windows 10 machine to check if the issue is specific to the Pi. According to some references (https://hallard.me/enable-serial-port-on-raspberry-pi/) using the serial port on the Pi can require a bit of work too.

**Comment by mra7072** [comment]
Yes, so I tried that and it allowed me to deduce the issue. I needed to add some delays otherwise it was timing out on the pi.

**Comment by mra7072** [comment]
Thank you again for your help!

**Comment by MatthieuDartiailh** [comment]
Great you could figure out a solution !
