### ISSUE TITLE
pyVISA: "PyUSB does not seem to be properly installed"

### ISSUE THREAD

**Issue by luzdal** [pyvisa/pyvisa#488]
Hello!

Trying to connect to a Keithley 2280S-60-3 device via USB. I encounter the seemingly common problem of initially getting a "()" shown in the screenshot below. I've found other threads that talk about this problem but end up working it out by using other programs instead, but I really need to get this working through pyvisa which in theory should be possible.

![Screen Shot 2020-01-15 at 3 59 36 PM](https://user-images.githubusercontent.com/26358351/72481821-7e3e3800-37b0-11ea-889c-1923de59155a.png)

So I tried **.get_instrument**:
![Screen Shot 2020-01-15 at 4 17 11 PM](https://user-images.githubusercontent.com/26358351/72482675-687e4200-37b3-11ea-98dd-d2e3654fce1d.png)
Which gives the following error:
<span style="color: red">VisaIOError</span>: VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.

Skimmed through the pyvisa [documentation](https://readthedocs.org/projects/pyvisa/downloads/pdf/latest/#page=33&zoom=100,96,96) which mentions something about "configuring the backend" (sect 1.1.2). Not sure what that means exactly but this is what I think they suggest is to try **.ResourceManager('@py')**:

![Screen Shot 2020-01-15 at 4 30 53 PM](https://user-images.githubusercontent.com/26358351/72483011-6c5e9400-37b4-11ea-8872-7387e6743c59.png)
Which gives the new error:
ValueError: PyUSB does not seem to be properly installed.
Please refer to PyUSB documentation and 
install a suitable backend like 
libusb 0.1, libusb 1.0, libusbx, 
libusb-win32 or OpenUSB.
No backend available

This is my pyvisa-info:
![Screen Shot 2020-01-15 at 3 56 27 PM](https://user-images.githubusercontent.com/26358351/72483069-9e6ff600-37b4-11ea-8ca9-bb88bbb36ec0.png)

I also tried **pip install pyusb** (ref. PyUSB "[documentation](https://github.com/pyusb/pyusb)") which returns:
Requirement already satisfied: pyusb in /Users/air/anaconda3/lib/python3.6/site-packages (1.0.2)

SOS!

**Comment by luzdal** [comment]
Realized that having NI VISA simultaneously communicating to the Keithley USB device will prevent pyvisa from reading it. Closed NI VISA and now pyvisa is showing the device with **rm.list_resources()**

**Comment by MatthieuDartiailh** [comment]
Happy you made it work !

**Comment by ScotchWhiskey** [comment]
Any answer to the above question. I think I have the same problem!

**Comment by MatthieuDartiailh** [comment]
What happens is that is NI-VISA claims the USB interface, pyusb does not see it anymore. You probably need to stop all background process from NI-VISA.

Honestly if you have NI-VISA installed and running just use the ivi backend. It is much more stable and using the python backend will not bring you anything.

**Comment by joctavio287** [comment]
Hello, I'm having the same problem but I don't know how to stop NI-VISA

**Comment by MatthieuDartiailh** [comment]
As I mentioned in my earlier answer if you have NI-VISA installed and running simply use it rather than trying to use pyvisa-py. The conflict handling for USB resources does not make it worthwhile.

**Comment by Julesghes** [comment]
Hey 
I installed NI-VISA but I still have this problem. 
it is to control Tektronic afg3102
do you any idea ?

**Comment by MatthieuDartiailh** [comment]
Please open a new issue following the template so that I have enough information to answer.
