### ISSUE TITLE
add documentation of default baudrate for SerialInstrument

### ISSUE THREAD

**Issue by hkennyv** [pyvisa/pyvisa#556]
It seems like this was actually present in an older version of the docs (see [1.4 docs](https://pyvisa.readthedocs.io/en/1.4/pyvisa.html#:~:text=The%20communication%20speed%20in%20baud,The%20default%20value%20is%209600.)). I'm not sure why it was removed, but I think it'd be nice to have that included in both the [SerialInstrument](https://pyvisa.readthedocs.io/en/1.4/pyvisa.html#:~:text=The%20communication%20speed%20in%20baud,The%20default%20value%20is%209600.) documentation and the [Communicating with your instrument](https://pyvisa.readthedocs.io/en/latest/introduction/communication.html) guide.

It took a little bit of digging to figure it out myself and I think that the Communication guide is often one of the first things that people read. I'd be happy to contribute this myself if there's interest :)

**Comment by MatthieuDartiailh** [comment]
Sure make a PR I will be happy to review it.
