### ISSUE TITLE
pkg_resources

### ISSUE THREAD

**Issue by ilanbiala** [pyvisa/pyvisa#563]
On minimal Python installations used in some Docker images, `setuptools` is not explicitly installed, and this package does not currently specify `setuptools` as a dependency, so `import pkg_resources` throws an error.

To Reproduce
--------------
1. Download/create a minimal Docker image that doesn't provide `setuptools` by default, and install `pyvisa`.
2. Launch the container and open a Python REPL, and `import pyvisa`.
3. See error

**Output of `pyvisa-info`**
```
"<filepath>", line 14, in <module>
    import visa
  File "<filepath>/site-packages_pypi__36__pyvisa_1_10_1/visa.py", line 16, in <module>
    from pyvisa import logger, __version__, log_to_screen, constants
  File "<filepath>/site-packages_pypi__36__pyvisa_1_10_1/pyvisa/__init__.py", line 18, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

The proper fix here is probably just to add `setuptools >= x.y.z` to https://github.com/pyvisa/pyvisa/blob/master/setup.cfg#L50-L53 so that `setuptools` is downloaded as a dependency when this package is installed.

**Comment by MatthieuDartiailh** [comment]
This is not the case anymore in pyvisa 1.11 in which we use importlib.metadata (except if you use the shell, which is something I will fix soon).

Feel free to reopen if you have more to report.
