### ISSUE TITLE
How to get VI_ATTR_RSRC_NAME for 32-bit Python

### ISSUE THREAD

**Issue by ThomasGund** [pyvisa/pyvisa#597]
Hi, 
I am using the following code to get VI_ATTR_RSRC_NAME:

``` python
import pyvisa

rm = pyvisa.ResourceManager()
print('VI_ATTR_RSRC_NAME: ',
      rm.visalib.get_attribute(session = 1, attribute = 0xBFFF0174)[0])
```

but this only works for 64 bit Python. How can I get it to work for 32 bit? 
And; is there any easier way to get VI_ATTR_RSRC_NAME?

**Comment by MatthieuDartiailh** [comment]
Hi,
All constants are defined in pyvisa.constants and also grouped in enum, and resource name value is 0xBFFF0002 which fits in a uint32 and should work on 32-bits. Resources also have a `resource_name` attribute for easier access. Note however that from your snippet I am not sure what you are trying to do. The resource manager does not have a resource name and you have not opened any resource.

**Comment by MatthieuDartiailh** [comment]
If you never connected to a resource you cannot get that level of information. If you are on USBTMC the address already encode the manufacturer id, but for a resource on TCPIP you cannot know anything before connecting to the resource from just the IP.

**Comment by ThomasGund** [comment]
Hi,
I am trying to read VI_ATTR_RSRC_MANF_NAME without being connected to a VISA resource. Then I am not depend on being connected to a VISA resource to see which VISA vendor I am using. That is convenient if my script is unable to find or connect to a VISA resource. It should be possible to get the following attributes without being connected to a VISA resource:
VI_ATTR_RSRC_IMPL_VERSION		
VI_ATTR_RSRC_MANF_NAME			
VI_ATTR_RSRC_MANF_ID			

For R&S VISA, which I am using, they should give:
0x500c03
Rohde & Schwarz Gmbh
0xfaf

``` python
import pyvisa
import sys

print(sys.version)		# Get Python version

rm = pyvisa.ResourceManager()
print('VI_ATTR_RSRC_NAME: ',
      rm.visalib.get_attribute(session = 1, attribute = 0xBFFF0174)[0])
```

Will give the following output in IDLE for 64 bit Python:
``` 
=============== RESTART: G:\Python\PyVISA\PyVISA_get-attribute.py ==============
3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
VI_ATTR_RSRC_NAME:  Rohde & Schwarz GmbH
```

When using Keysight VISA:
```
=============== RESTART: G:\Python\PyVISA\PyVISA_get-attribute.py ==============
3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
VI_ATTR_RSRC_NAME:  Keysight Technologies
```

When using 32 bit Python I get the following:
```
For 32 bit Python:
=============== RESTART: G:\Python\PyVISA\PyVISA_get-attribute.py ==============
3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)]
Traceback (most recent call last):
  File "G:\Python\PyVISA\PyVISA_get-attribute.py", line 8, in <module>
    rm.visalib.get_attribute(session = 1, attribute = 0xBFFF0174)[0])
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\pyvisa\ctwrapper\functions.py", line 839, in get_attribute
    ret = library.viGetAttribute(session, attribute, attribute_state)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 222, in _return_handler
    return self.handle_return_value(session, ret_value)  # type: ignore
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\pyvisa\highlevel.py", line 251, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_INV_OBJECT (-1073807346): The given session or object reference is invalid.
```

I thought that the problem maybe was related to 0xBFFF0174, which is has 64 bit length.

**Comment by ThomasGund** [comment]
Thanks @MatthieuDartiailh 
It worked with info = rm.visalib.get_debug_info(). Both for 64 and 32 bit Python. It is a better solution than I have used. I found my "metohod" by reading the PyVISA code and "trail and error" testing.

This is what I get with your code:

```
=============== RESTART: G:\Python\PyVISA\PyVISA_get-attribute.py ==============
3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
OrderedDict([('Version', '1.11.3 (bundled with PyVISA)'), ('#1: C:\\WINDOWS\\system32\\visa32.dll', OrderedDict([('found by', 'auto'), ('bitness', '64'), ('Vendor', 'Rohde & Schwarz GmbH'), ('Impl. Version', 'Rohde & Schwarz GmbH'), ('Spec. Version', 'Rohde & Schwarz GmbH')])), ('#2: C:\\WINDOWS\\system32\\visa64.dll', OrderedDict([('found by', 'auto'), ('bitness', '64'), ('Vendor', 'Rohde & Schwarz GmbH'), ('Impl. Version', 'Rohde & Schwarz GmbH'), ('Spec. Version', 'Rohde & Schwarz GmbH')]))])

```

It is interesting that vendor, impl.version, spec.version all says Rohde & Schwarz GmbH. Is this as expected? I would expected vendor to be Rohde & Schwarz Gmbh, impl.version to be 0x500c03 and spec.version to be 0x500800. That is what I get
when I am using RsVisaTester from R&S. 
![RsVisaConfigure](https://user-images.githubusercontent.com/80954754/117816513-e139c500-b266-11eb-9f55-563fe56ddc88.PNG)

We get the same result when running pyvisa-info from command window, only R&S is reported:
```
PyVISA Version: 1.11.3

Backends:
   ivi:
      Version: 1.11.3 (bundled with PyVISA)
      #1: C:\WINDOWS\system32\visa32.dll:
         found by: auto
         bitness: 64
         Vendor: Rohde & Schwarz GmbH
         Impl. Version: Rohde & Schwarz GmbH
         Spec. Version: Rohde & Schwarz GmbH
      #2: C:\WINDOWS\system32\visa64.dll:
         found by: auto
         bitness: 64
         Vendor: Rohde & Schwarz GmbH
         Impl. Version: Rohde & Schwarz GmbH
         Spec. Version: Rohde & Schwarz GmbH
```

**Comment by MatthieuDartiailh** [comment]
I noticed the issue with impl spec when answering you and made a PR. I will merge it shortly (having some cis issues at the moment)
