### ISSUE TITLE
[COM] Communication issue with BK Precision LCR Meter using Ethernet

### ISSUE THREAD

**Issue by jennbyford** [pyvisa/pyvisa#608]
Instrument details
------------------
* Model: BK Precision LCR Meter 894
* Communication: TCPIP (ethernet)
* Link to the documentation (if available): https://www.bkprecision.com/products/component-testers/894-500khz-lcr-meter.html

Output of `pyvisa-info`
-----------------------
Machine Details:
   Platform ID:    Windows-10-10.0.19041-SP0
   Processor:      Intel64 Family 6 Model 142 Stepping 10, GenuineIntel

Python:
   Implementation: CPython
   Executable:     c:\programdata\anaconda3\python.exe
   Version:        3.7.3
   Compiler:       MSC v.1915 64 bit (AMD64)
   Bits:           64bit
   Build:          Apr 24 2019 15:29:51 (#default)
   Unicode:        UCS4

PyVISA Version: 1.11.3

Backends:
   ivi:
      Version: 1.11.3 (bundled with PyVISA)
      #1: C:\WINDOWS\System32\visa32.dll:
         found by: auto
         bitness: 64
         Vendor: National Instruments
         Impl. Version: National Instruments
         Spec. Version: National Instruments
      #2: C:\WINDOWS\System32\visa64.dll:
         found by: auto
         bitness: 64
         Vendor: National Instruments
         Impl. Version: National Instruments
         Spec. Version: National Instruments

Description: Hi, I've been using PyVISA to successfully communication with this equipment via serial for some time. I need to move to an ethernet connection and have run into issues that I think are related to PyVISA. I am able to successfully add my instrument using NI-MAX and then use the VISA Interactive Control to send commands to the device that it responds to (like IDN? or TRG). I can also ping the device through cmd. So I know the device is connected AND NI-VISA softwares see it and can talk to it. In python using PyVISA it will list my instrument as a resource:
rm = pyvisa.ResourceManager()
print(rm.list_resources())
('TCPIP0::10.0.0.2::inst0::INSTR',)

Then if I try my_instrument = rm.open_resource('TCPIP0::10.0.0.2::inst0::INSTR') I get the following message:
VisaIOError: VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.

I have tried specifying the backend when I open the resource manager by using: rm = pyvisa.ResourceManager('C:\Windows\System32\\visa32.dll') (or the visa64.dll) but that has not helped. 

Any help would be appreciated as I am stumped.

**Comment by MatthieuDartiailh** [comment]
That sounds weird. I assume this the exact same resource name as used by NI Interactive control, right ? It should not matter but do you have interactive control while testing pyvisa ? If yes maybe try stopping it. For INSTR it should not matter but just in case.

**Comment by jennbyford** [comment]
It is the same resource name as is used by NI Interactive Control. I was keeping the interactive control open while testing pyvisa (so I could keep sanity checking myself) but I closed out of it completely and retried the open_source() command and it worked his time. I too feel that it shouldn't have mattered but I guess it does?! Thanks for your help!

**Comment by MatthieuDartiailh** [comment]
Happy I could help ! 

For SOCKET resources I know it does because you cannot open multiple connections to a SOCKET resource but for an INSTR it should have worked.
