### ISSUE TITLE
can't reach visa.constants?

### ISSUE THREAD

**Issue by bactone** [pyvisa/pyvisa#613]
Hi, i am new to pyvisa, and I trying to import the module and test the get_visa_attribute() method:
```python
import pyvisa as visa

rm = visa.ResourceManager()
inst9 = rm.open_resource('COM9')
print(inst9.get_visa_attribute(0xBFFF00E9))  # VI_ATTR_INTF_INST_NAME
```
in such a case ,I have to use "0xBFFF00E9" to represent attrubute name "VI_ATTR_INTF_INST_NAME"

but if i use the following code:

```python
import visa

rm = visa.ResourceManager()
inst9 = rm.open_resource('COM9')
print(inst9.get_visa_attribute(visa.constants.VI_ATTR_INTF_INST_NAME))  # VI_ATTR_INTF_INST_NAME
```
I can reach the attribute easily, but it reports a FutureWarning: The visa module provided by PyVISA is being deprecated.

so my question is how to reach attribute names in constants when using import pyvisa.

**Comment by MatthieuDartiailh** [comment]
The visa module is deprecated because it can conflict from the visa package (related to VISA credit/debit cards). Instead of importing from visa import from pyvisa as:
```python
import pyvisa
from pyvisa import constants

rm = pyvisa.ResourceManager()
inst9 = rm.open_resource('COM9')
print(inst9.get_visa_attribute(constants.VI_ATTR_INTF_INST_NAME))  # VI_ATTR_INTF_INST_NAME
 ```

**Comment by bactone** [comment]
@MatthieuDartiailh thanks, got it
