### ISSUE TITLE
SR830 lockin amplifier connection to PC using PyVisa

### ISSUE THREAD

**Issue by aksivan** [pyvisa/pyvisa#621]
I am trying to connect the SR830 Lock-in Amplifier to the PC to automate some experiments. I am using an RS232(on the lockin) - USB (on the PC) for the connection. Now I want to see if the connection is okay. I amgetting a timeout error for the read command. Has anyone experienced this?

import pyvisa as visa
rm = visa.ResourceManager()
rm.list_resources()
print(rm)
    Resource Manager of Visa Library at C:\WINDOWS\system32\visa32.dll
print(rm.list_resources())
   ('ASRL3::INSTR', 'ASRL4::INSTR')
my_instrument = rm.open_resource('ASRL4::INSTR')
print(my_instrument)
  SerialInstrument at ASRL4::INSTR
my_instrument.read_termination = '\r'
my_instrument.write_termination = '\r\n'
my_instrument.write('*IDN?')
  7
my_instrument.read('*IDN?')

  ---------------------------------------------------------------------------
VisaIOError                               Traceback (most recent call last)
<ipython-input-13-b8b8eb823f80> in <module>
----> 1 my_instrument.read('*IDN?')

~\Anaconda3\lib\site-packages\pyvisa\resources\messagebased.py in read(self, termination, encoding)
    487         else:
    488             with self.read_termination_context(termination):
--> 489                 message = self._read_raw().decode(enco)
    490 
    491         if not termination:

~\Anaconda3\lib\site-packages\pyvisa\resources\messagebased.py in _read_raw(self, size)
    440                         status,
    441                     )
--> 442                     chunk, status = self.visalib.read(self.session, size)
    443                     ret.extend(chunk)
    444             except errors.VisaIOError as e:

~\Anaconda3\lib\site-packages\pyvisa\ctwrapper\functions.py in read(library, session, count)
   2335     buffer = create_string_buffer(count)
   2336     return_count = ViUInt32()
-> 2337     ret = library.viRead(session, buffer, count, byref(return_count))
   2338     return buffer.raw[: return_count.value], ret
   2339 

~\Anaconda3\lib\site-packages\pyvisa\ctwrapper\highlevel.py in _return_handler(self, ret_value, func, arguments)
    220                 session = None
    221 
--> 222         return self.handle_return_value(session, ret_value)  # type: ignore
    223 
    224     def list_resources(

~\Anaconda3\lib\site-packages\pyvisa\highlevel.py in handle_return_value(self, session, status_code)
    249 
    250         if rv < 0:
--> 251             raise errors.VisaIOError(rv)
    252 
    253         if rv in self.issue_warning_on:

VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

**Comment by MatthieuDartiailh** [comment]
For serial you need to be sure the baud rate and parity match the setting on your instrument. Also it appears from the documentation (https://www.thinksrs.com/downloads/pdfs/manuals/SR830m.pdf) that you can enable CTS or DTR (or both but I am not sure there) control flow.
I also assume you checked the serial port number by plugin unplugging the USB on the computer side.

**Comment by aksivan** [comment]
Many thanks for the reply, I did set all the values as it is on the instrument. We reset the queue by pressing the setup button, but we are still having the time-out error.



________________________________

**Comment by MatthieuDartiailh** [comment]
Can you try reading one byte at a time using read_bytes(1) to see if the instrument is answering at all ?

**Comment by aksivan** [comment]
Dear Matthieu,


It didn't work, I set the termchar, cleared the buffer manually using the setup button as in the manual, and tried to read a byte, but the timeout message still comes up. So I decided to try with the NIMax, and now upon query, I can still get the error message as shown in the image but the instrument however I can see the IDN. But when I try this in the visa shell I am still getting the timed out error.


-Best


________________________________

**Comment by MatthieuDartiailh** [comment]
The attachment did not go through, can you repost it directly on Github ?

**Comment by aksivan** [comment]
Finally managed to sort it using pyserial instead of pyvisa :) Thank you for your help.
