### ISSUE TITLE
Macbook , They are all 64bits, but tips 'no matching architecture in universal wrapper'

### ISSUE THREAD

**Issue by tangtangtang11** [pyvisa/pyvisa#655]
Machine Details:
   Platform ID:    macOS-11.2.3-arm64-arm-64bit
   Processor:      arm

Python:
   Implementation: CPython
   Executable:     /opt/homebrew/opt/python@3.9/bin/python3.9
   Version:        3.9.9
   Compiler:       Clang 13.0.0 (clang-1300.0.29.3)
   Bits:           64bit
   Build:          Nov 21 2021 03:16:13 (#main)
   Unicode:        UCS4

PyVISA Version: 1.11.3

Backends:
   ivi:
      Version: 1.11.3 (bundled with PyVISA)
      #1: /Library/Frameworks/visa.framework/visa:
         found by: auto
         bitness: 64
         Could not get more info: Interpreter and library have different bitness.

import pyvisa
rm = pyvisa.ResourceManager('/Library/Frameworks/VISA.framework/VISA')
rm.list_resources()

OSError: dlopen(/Library/Frameworks/VISA.framework/VISA, 6): no suitable image found.  Did find:
	/Library/Frameworks/VISA.framework/VISA: no matching architecture in universal wrapper
	/Library/Frameworks/VISA.framework/VISA: no matching architecture in universal wrapper
	/Library/Frameworks/VISA.framework/Versions/A/VISA: no matching architecture in universal wrapper

**Comment by MatthieuDartiailh** [comment]
I do not own a Mac M1 but my best guess is that your python is built for arm but that NI does not provide a native arm build.

You can try installing x86-64 python and see if it helps.

We should try to get more details than just the bitness now that Apple can have that kind of mismatch, too. If you figure out a way to get the full architecture for both python and the dylib feel free to make a PR.

**Comment by akira-okumura** [comment]
PyVISA + NI-VISA works on M1/M2 Macs if x86_64 Python is used.
