### ISSUE TITLE
PyPi: Project Links: changelog link is broken, returns error 404.

### ISSUE THREAD

**Issue by dphaas** [pyvisa/pyvisa#671]
PyPi: Project Links: changelog link is broken, returns error 404.

**Comment by MatthieuDartiailh** [comment]
Thanks for reporting. I will check ASAP.

**Comment by MatthieuDartiailh** [comment]
I corrected the issue in the repo. I will wait a couple of weeks before making a patch release to fix the issue on PyPI in case I missed anything else. Feel free to ping me if I forget to make the release.
