### ISSUE TITLE
question of reading bytes from instrument

### ISSUE THREAD

**Issue by Max1993914** [pyvisa/pyvisa#684]
Hello.

I checked pyvisa doc and notice that read() has a parameter called count. I'm wondering how many bytes can I read maximumlly from instrument if I keep this parameter default?

**Comment by MatthieuDartiailh** [comment]
The VISA C API define the count argument as a uint32. Using pyvisa you would however not go through the library object directly but use a resource that will use the chunk size by default and perform multiple reads if necessary. Does that answer your question ?

**Comment by MatthieuDartiailh** [comment]
Feel free to reopen if you need more details.
