### ISSUE TITLE
Is there any way to add a variable into the write command?

### ISSUE THREAD

**Issue by ejulian86** [pyvisa/pyvisa#693]
For example I have this power supply and I want to change the voltage of it through python input command. For example I have the follow script in a for loop: 

inputV = input("Output Voltage (V): ")
myinstrument.write('SOUR:VOLT somename', inputV)

Is is possible to do something like that? I am struggling to find the answer online...

Cheers

**Comment by MatthieuDartiailh** [comment]
The simplest is to use an f-string:
```python
inputV = input("Output Voltage (V): ")
myinstrument.write(f'SOUR:VOLT {inputV}')
```
Obviously you should check the input is meaningful before sending it.

**Comment by ejulian86** [comment]
Thanks! That worked perfect fine!!
