### ISSUE TITLE
Adjusting Trigger Level

### ISSUE THREAD

**Issue by tawseefpatel** [pyvisa/pyvisa#696]
https://www.keysight.com/us/en/support/MSOX4104A/mixed-signal-oscilloscope-1-ghz-4-analog-16-digital-channels.html#drivers
pyvisa v1.12

This is the oscilloscope i have. i am to wanting to look into if it is possible to adjust the trigger level via pyvisa. i noticed there are the read and write functions but i cannot find the data commands to pass through. 

the task i want to complete is i want to set trigger level to 5mV and retrieve the frequency and increase trigger level until frequency is 1Hz. what commands would be necessary for that?

**Comment by MatthieuDartiailh** [comment]
You want to look at this manual for SCPI commands supported by your instrument: https://www.keysight.com/fr/en/assets/9018-06976/programming-guides/9018-06976.pdf

For triggering you have `:TRIGger:LEVel:HIGH` for example and for measurements `:MEASure:FREQuency` is likely a good starting point.
