### ISSUE TITLE
Event Handling With Callback Handler Not Working

### ISSUE THREAD

**Issue by fabiangeissler** [pyvisa/pyvisa#702]
Hello,
I am trying to use the operation complete service request on a Rohde&Schwarz network analyzer. I tried the examples listed in [the documentation](https://pyvisa.readthedocs.io/en/1.12.0/introduction/event_handling.html). The version with wait_on_event works, but the version with a callback handler does not. The callback function is never executed. The backend I use is NI Visa. Event is triggered as wait_on_event in the same scenario is working.

I dont know where to start debugging here. Seems like a problem with the callback mechanism but there is no error or any further information.

Code (similar to example):
```python
from time import sleep
from pyvisa import ResourceManager, constants

rm = ResourceManager()

def handle_event(resource, event, user_handle):
    resource.called = True
    print(f"Handled event {event.event_type} on {resource}")

with rm.open_resource('TCPIP::192.168.2.2::INSTR') as instr:

    instr.called = False

    # Type of event we want to be notified about
    event_type = constants.EventType.service_request
    # Mechanism by which we want to be notified
    event_mech = constants.EventMechanism.queue

    wrapped = instr.wrap_handler(handle_event)

    user_handle = instr.install_handler(event_type, wrapped, 42)
    instr.enable_event(event_type, event_mech, None)

    print(user_handle)

    # Instrument specific code to enable service request
    # (for example on operation complete OPC)
    instr.write('*SRE 32;*ESE 1')
    instr.write("*CLS;INIT;*OPC")

    while not instr.called:
        sleep(1)

    instr.disable_event(event_type, event_mech)
    instr.uninstall_handler(event_type, wrapped, user_handle)
```

**Comment by MatthieuDartiailh** [comment]
The docs may be wrong here but you need to use `constants.EventMechanism.handler` when enabling events for events to be sent to the handler you installed. Let me know if this helps.

**Comment by fabiangeissler** [comment]
Thank you for the quick response. Yes that solves the problem. In that case the documentation should be updated.

**Comment by MatthieuDartiailh** [comment]
Thanks. If you feel so inclined feel free to make a PR against the docs, otherwise I will try to come back to it at one point.
