### ISSUE TITLE
How can I get access to the constants defined in constants.py from user code?

### ISSUE THREAD

**Issue by sidneycadot** [pyvisa/pyvisa#72]
How can an application script gain access to the constants defined in 'constants.py' (in order to use level 1/2 functions)?

I can't find examples that do this. Tried several things (eg. import visa.constants) but to no avail.

(using version 1.6.0dev0).

**Comment by TonyBeswick** [comment]
Any update on this? accessing constants via visa (rather than pyvisa) doesn't appear to be implemented yet.

**Comment by hgrecco** [comment]
Done. It will be included in 1.6.4 (in about a month or so), but you can install from git

**Comment by TonyBeswick** [comment]
Much appreciated, thanks.
