### ISSUE TITLE
ViBusAddress configured ctypes is incorrect in 64 bit machine

### ISSUE THREAD

**Issue by karthikr-vti** [pyvisa/pyvisa#724]
In 64 bit machine, ctypes for ViBusAddress is incorrect. For example, this causes visalib.move calls to truncate pointers while transferring data from host to target machine. 

types from VISA.h(from Include file for the VISA Library 7.2 specification)

```
#if defined(_VI_INT64_UINT64_DEFINED) && defined(_VISA_ENV_IS_64_BIT)
typedef ViUInt64             ViBusAddress;
typedef ViUInt64             ViBusSize;
typedef ViUInt64             ViAttrState;
#else
typedef ViUInt32             ViBusAddress;
typedef ViUInt32             ViBusSize;
typedef ViUInt32             ViAttrState;
#endif`
```
ctypes from pyvisa:
from [https://github.com/pyvisa/pyvisa/blob/645c1c648870dac4caffa2c65241638ef273f981/pyvisa/ctwrapper/types.py#L109](url)

`ViBusAddress, ViPBusAddress = _type_pair(ViUInt32)`

**Comment by MatthieuDartiailh** [comment]
This is indeed wrong. Could you make a PR to fix it ? I do not have access to registrer based resources to test such a change.
