### ISSUE TITLE
Dev environment setup instructions are outdated

### ISSUE THREAD

**Issue by arr-ee** [pyvisa/pyvisa#810]
Stumbled upon this while rebuilding my dev env working on something else: https://pyvisa.readthedocs.io/en/latest/faq/contributing.html#contribute-code references `setup.py`, which does not exist anymore.

We also seem to be lacking `pytest` in `dev-requirements.txt`.

Could also use this opportunity to move/copy that part to a [`CONRTRIBUTING` file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#adding-a-contributing-file)

**Comment by arr-ee** [comment]
+ update checklist in the PR template

**Comment by MatthieuDartiailh** [comment]
In addition to #814 I subscribed to pre-commit.ci to avoid delayed updates to pre-commit configuration

**Comment by arr-ee** [comment]
Awesome, thank you!
