### ISSUE TITLE
read_termination is not set while connect via socket

### ISSUE THREAD

**Issue by kostochkin** [pyvisa/pyvisa#98]
Hi,
I think it's a bug:

``` console
>>>import visa
>>>rm = visa.ResourceManager()
>>>i = rm.open_resource("TCPIP::192.168.255.233::5025::SOCKET")
>>>i.read_termination
>>>i.query("*IDN?")
......some output
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.
>>> i.read_termination = '\n'
>>> i.query("*IDN?")
u'Cool instrument'
```

**Comment by JerPatton** [comment]
Hello,

I just wanted to mention that I just had the exact same issue with current version 1.14.1.

I am connecting to an instrument with a TCPIPSocket resource as follows:
`device = rm.open_resource("TCPIP::192.168.255.233::5025::SOCKET")`. 
But I receive a `pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.` during the `"*IDN?"` query...

It solves the issue if I manually set (at least) the write_termination to '\n' via `device.read_termination = '\n'`.

Cheers
